{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.18-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.18-test.aar",
          "url": "logging-0.0.18-test.aar",
          "size": 33959,
          "sha512": "40647d5a6c8a7b0c8b9720548224cdeb5c97f5098bd12e12a778f0bcf6254a38c9a03e7b9d5a3094563d94916ec45c54d817c940561d9ac2c99d6efa3f29995a",
          "sha256": "030fdccc4e11011be8c977d60034b218e10c57824ee2f1945a7c02878df117f9",
          "sha1": "153e169a924123ddc5df2d79b52c39590e8546aa",
          "md5": "57cbab8bc877b0e53e625dfcfce52ce3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.18-test.aar",
          "url": "logging-0.0.18-test.aar",
          "size": 33959,
          "sha512": "40647d5a6c8a7b0c8b9720548224cdeb5c97f5098bd12e12a778f0bcf6254a38c9a03e7b9d5a3094563d94916ec45c54d817c940561d9ac2c99d6efa3f29995a",
          "sha256": "030fdccc4e11011be8c977d60034b218e10c57824ee2f1945a7c02878df117f9",
          "sha1": "153e169a924123ddc5df2d79b52c39590e8546aa",
          "md5": "57cbab8bc877b0e53e625dfcfce52ce3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logging-0.0.18-test-sources.jar",
          "url": "logging-0.0.18-test-sources.jar",
          "size": 20073,
          "sha512": "66593b4760e70990be54d1bd950e5ad5d6d0f2d46f707bdca318354cd3d2ec661364d19bc06983fe2cc1e0842b8ccdba9340154d1b2ccc315da8865cff4703a0",
          "sha256": "b9d1f7daee71c11146ee04dce4a50648205b3012918e60d3298dec2f16793599",
          "sha1": "ff34506351c1bf95c6136942050f5f315781755a",
          "md5": "71200ec33326844cc873fa3226adaa64"
        }
      ]
    }
  ]
}
