{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.8.aar",
          "url": "remote-0.0.8.aar",
          "size": 8519,
          "sha512": "23d487ed3cf0749c08f743a2dd9d6a898d1794c103a165a3b4f520bd6a961b772178cc8c97392abf5f8e4e025d531721ee59c9723553000162a538b3075c9370",
          "sha256": "dd692fd58cb7e7cdbf1a1b2861b73f0a33acfaa74ba12832755d5e43f5ef8f75",
          "sha1": "6a871e00f0ecaf143603bdafb8f999f3eefd1ba6",
          "md5": "b29672bde213b42980ab9d3010e0af6f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.8.aar",
          "url": "remote-0.0.8.aar",
          "size": 8519,
          "sha512": "23d487ed3cf0749c08f743a2dd9d6a898d1794c103a165a3b4f520bd6a961b772178cc8c97392abf5f8e4e025d531721ee59c9723553000162a538b3075c9370",
          "sha256": "dd692fd58cb7e7cdbf1a1b2861b73f0a33acfaa74ba12832755d5e43f5ef8f75",
          "sha1": "6a871e00f0ecaf143603bdafb8f999f3eefd1ba6",
          "md5": "b29672bde213b42980ab9d3010e0af6f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-0.0.8-sources.jar",
          "url": "remote-0.0.8-sources.jar",
          "size": 7120,
          "sha512": "a7ff3fde5ad27402bd0bb8efef5ff99b723c62e33f5fd49ceaa8f709cdb8ef56013f9b33992f470a5a36294616233e40fc1640d17e45e042e5ebb4132e02b665",
          "sha256": "5a7a9589681c0e81d97c2ef1954eba216051eabcd3419785a00caa965d3b3b4d",
          "sha1": "3fd6189185df9452b3a2e0fbc93f7aceafeefac2",
          "md5": "94451feea8a34d63a03b11eccd4e3ab9"
        }
      ]
    }
  ]
}
