{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "0.0.1-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.1-snapshot.aar",
          "url": "data-0.0.1-snapshot.aar",
          "size": 168837,
          "sha512": "f8f20005c62f3f132d9f6ba652178065bb33d9396505dc2596dba1addbae39a84875cfaafbaca77639903665922136825bf467751979234b3a3c3416a8f9f9be",
          "sha256": "929a39f2f3d5133e62b88b6c3f2d026cbd6bf829b9e1eacba48600545d3ea29b",
          "sha1": "b5dd4b3885cbedddb536337dad92a22474a3ba9c",
          "md5": "092ca96a7541221fb8824603727e4d94"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.1-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.1-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "0.0.1-snapshot"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.1-snapshot.aar",
          "url": "data-0.0.1-snapshot.aar",
          "size": 168837,
          "sha512": "f8f20005c62f3f132d9f6ba652178065bb33d9396505dc2596dba1addbae39a84875cfaafbaca77639903665922136825bf467751979234b3a3c3416a8f9f9be",
          "sha256": "929a39f2f3d5133e62b88b6c3f2d026cbd6bf829b9e1eacba48600545d3ea29b",
          "sha1": "b5dd4b3885cbedddb536337dad92a22474a3ba9c",
          "md5": "092ca96a7541221fb8824603727e4d94"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-0.0.1-snapshot-sources.jar",
          "url": "data-0.0.1-snapshot-sources.jar",
          "size": 14179,
          "sha512": "f410eaad27e4cdb19bf17fa307a1b374ed6dbfed3af8a2a96924dc0486274a60fc46227615b2eb09c1785e420d6124b0d112f77dff779174727f9d13efb57df5",
          "sha256": "a9e47e781e71abb943eca825f23ed7220a02faeda4112f24826a5acbb5c5f8fe",
          "sha1": "9b656fe0dbe376e75f755e0e17dd8412a3a28a5f",
          "md5": "a291f367902d40be7cc8319bacead56d"
        }
      ]
    }
  ]
}
