{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.19.aar",
          "url": "utils-0.0.19.aar",
          "size": 68562,
          "sha512": "82a8c9a3453c26b965539309421bbf7d1231c71215145479098728af3e546b2f04e0c30db97bb429b45e7c46fdb71e47e5fb3ec882b1d5e7005a30642f67f2ba",
          "sha256": "9d408be3cf63c683b6c18c07ca490ea60c92bd4750ea0b8339a02faab78b1dfe",
          "sha1": "46a9951eefe3ad4ba216b25f40f1b71cdc9a1e80",
          "md5": "cc651912faaaa34c0a5429b005cc3bb4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.19.aar",
          "url": "utils-0.0.19.aar",
          "size": 68562,
          "sha512": "82a8c9a3453c26b965539309421bbf7d1231c71215145479098728af3e546b2f04e0c30db97bb429b45e7c46fdb71e47e5fb3ec882b1d5e7005a30642f67f2ba",
          "sha256": "9d408be3cf63c683b6c18c07ca490ea60c92bd4750ea0b8339a02faab78b1dfe",
          "sha1": "46a9951eefe3ad4ba216b25f40f1b71cdc9a1e80",
          "md5": "cc651912faaaa34c0a5429b005cc3bb4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.19-sources.jar",
          "url": "utils-0.0.19-sources.jar",
          "size": 37974,
          "sha512": "a74870acd1ed5c72cf704d1432bb107cb35f1dafd21ac33aad24f66c65581eee3d4280db528ab886523c6724ff3b4dde56252dcae5ca1315e5eb33bdce6e9388",
          "sha256": "24182c82150d7eed56b15acfcfa9c9e625d146d56e0008e45b85a7cd3d5dc88d",
          "sha1": "865d4f78e4a31c4d43a81fa3ae013f3d80ad1239",
          "md5": "8bb6b7d3240206cf9f996a51a46ee53e"
        }
      ]
    }
  ]
}
