{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.19.aar",
          "url": "utils-0.0.19.aar",
          "size": 68356,
          "sha512": "05b558be3bc599d6120efa2c33ba283e5651b4daf18bb0e0a8494f2086d38269224868d64865299ac4a1fb99116bb289970b9d1c7e22565c1062aeb177776fc5",
          "sha256": "5430500a1b9c331d5122778161271a62a835c2fe04f497d33f71b0ec5071786b",
          "sha1": "2dcb4c1ba0ef13a791388b81682baa8b36cb35f7",
          "md5": "eb8dc7e452666c115b23da986831dec3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.19.aar",
          "url": "utils-0.0.19.aar",
          "size": 68356,
          "sha512": "05b558be3bc599d6120efa2c33ba283e5651b4daf18bb0e0a8494f2086d38269224868d64865299ac4a1fb99116bb289970b9d1c7e22565c1062aeb177776fc5",
          "sha256": "5430500a1b9c331d5122778161271a62a835c2fe04f497d33f71b0ec5071786b",
          "sha1": "2dcb4c1ba0ef13a791388b81682baa8b36cb35f7",
          "md5": "eb8dc7e452666c115b23da986831dec3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.19-sources.jar",
          "url": "utils-0.0.19-sources.jar",
          "size": 37806,
          "sha512": "1f53b15bf79ae125d0b2b139aaa8f4634c8d896f48e51580be9b9a0fbd9fba7388b2bd864a67881193591f90e3d9b0ee05109a193b0586c8744a321743380da5",
          "sha256": "b27f12ebf51f9e1816742a649d49b68b6dec44288470fa1a0e19611c06e3858a",
          "sha1": "d5b4566440f5aee74f0dd5be5fb5a1169b790942",
          "md5": "b17cd7cb886b4b97350e7c6d918cdbd1"
        }
      ]
    }
  ]
}
