{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.3.0.aar",
          "url": "data-1.3.0.aar",
          "size": 219661,
          "sha512": "81991f8d50f09cfcf7f0bce196696fce7d102c6966cbafaf07883a5b4f90069d3f9a6866d885386f62471fad74256767c6f4f5cf63407a97c09fbc6b365dd0bd",
          "sha256": "4e0e0554d74ddaebc1c7bf409707296f9b438d6a88d3d324b5477e136d93c2c6",
          "sha1": "12a00143a0be6dab09494fe737e879b7f91c07f0",
          "md5": "59a1610941f82da14c8301b29220db15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.3.0.aar",
          "url": "data-1.3.0.aar",
          "size": 219661,
          "sha512": "81991f8d50f09cfcf7f0bce196696fce7d102c6966cbafaf07883a5b4f90069d3f9a6866d885386f62471fad74256767c6f4f5cf63407a97c09fbc6b365dd0bd",
          "sha256": "4e0e0554d74ddaebc1c7bf409707296f9b438d6a88d3d324b5477e136d93c2c6",
          "sha1": "12a00143a0be6dab09494fe737e879b7f91c07f0",
          "md5": "59a1610941f82da14c8301b29220db15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.3.0-sources.jar",
          "url": "data-1.3.0-sources.jar",
          "size": 31464,
          "sha512": "2826d00f970217882c31f2e2ac48ad4a14094e153e8263965fc3f9435fda34dffe34194a37ffca64743d9d41e0ee2fe419ccc46dbc6e5d76925c90fb9a1a5c1f",
          "sha256": "bd3bcd0a0f5a633fac23e99d241d9bc331b87d0b493f02003094275b1a60195f",
          "sha1": "d42e53b426a693a0b03a9f489dba4660e9e384c9",
          "md5": "2bfd10c90b258641a446d2af0d9f61f5"
        }
      ]
    }
  ]
}
