{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "0.0.14-ofuscated-test-6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.14-ofuscated-test-6.aar",
          "url": "designsystem-0.0.14-ofuscated-test-6.aar",
          "size": 1876966,
          "sha512": "f119e67a3cf7eb4a5cd9de440f6050fc59efa46f323fb99be181edd0d3b3996bbf3a52a6d87530ffcd4f244d1fc4bfcffe9179dc5a58d3f4067733eca3ac6648",
          "sha256": "bf521f301890c8438db9c4c20eb680e901e31b81f7e53dcdb904aff8efe091f1",
          "sha1": "67dc282e5785b09099f863f6618af8682a86c433",
          "md5": "b64a66abef71ea8d813a4dee1507fbeb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.14-ofuscated-test-6.aar",
          "url": "designsystem-0.0.14-ofuscated-test-6.aar",
          "size": 1876966,
          "sha512": "f119e67a3cf7eb4a5cd9de440f6050fc59efa46f323fb99be181edd0d3b3996bbf3a52a6d87530ffcd4f244d1fc4bfcffe9179dc5a58d3f4067733eca3ac6648",
          "sha256": "bf521f301890c8438db9c4c20eb680e901e31b81f7e53dcdb904aff8efe091f1",
          "sha1": "67dc282e5785b09099f863f6618af8682a86c433",
          "md5": "b64a66abef71ea8d813a4dee1507fbeb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "designsystem-0.0.14-ofuscated-test-6-sources.jar",
          "url": "designsystem-0.0.14-ofuscated-test-6-sources.jar",
          "size": 41489,
          "sha512": "fe32674c9f31803a661ec9cec5a345a38aeaaf337273c668330798497828c295e7e3a05b6f6817b2df3fac386811914e2bee2d5e50a295aec73f608ff726e30c",
          "sha256": "6c21a43a13bb36e8d475b6fc9adf57740a6d00d490e00ada9a387c798832fe1f",
          "sha1": "e8bf792ee118fe4a62c1b3081482d9e31bd603da",
          "md5": "ad63ff4c46149ee0dbebe18708d4e08b"
        }
      ]
    }
  ]
}
