{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "network",
    "version": "2.0.0-beta-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.0.0-beta-4.aar",
          "url": "network-2.0.0-beta-4.aar",
          "size": 29350,
          "sha512": "cff60ebd7925ac6b5b14aaae12eba200309e7db25bdb08a059dbb18db5244e216c50397afd5e11a11c65ef5fe0483a46afc2728bf2a1adfd4ed0cc6e53212df7",
          "sha256": "3dca88c7c19fc7235a91c88c76446c9dff94933efe2fe4fc9686aa6b70ba3b92",
          "sha1": "bc95a73c3d3eca17f09736468e94bac3c52a827d",
          "md5": "7071c66bf6a5c7aba64ee9c0ad63cc03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.0-beta-4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.0.0-beta-4.aar",
          "url": "network-2.0.0-beta-4.aar",
          "size": 29350,
          "sha512": "cff60ebd7925ac6b5b14aaae12eba200309e7db25bdb08a059dbb18db5244e216c50397afd5e11a11c65ef5fe0483a46afc2728bf2a1adfd4ed0cc6e53212df7",
          "sha256": "3dca88c7c19fc7235a91c88c76446c9dff94933efe2fe4fc9686aa6b70ba3b92",
          "sha1": "bc95a73c3d3eca17f09736468e94bac3c52a827d",
          "md5": "7071c66bf6a5c7aba64ee9c0ad63cc03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "network-2.0.0-beta-4-sources.jar",
          "url": "network-2.0.0-beta-4-sources.jar",
          "size": 15773,
          "sha512": "24ffb20829c35fb8828791b644f3cdf452781f80ce487ec53095dfffb682e836c97b67a416bb1474cfb24c1f4e7625d5917d362caac37ccb0aff5eed928c5f2b",
          "sha256": "1ed354974a90302f4ae16630b6958bc2190d1ba1527fd5549edffc379a6251ed",
          "sha1": "8b08985160cef49e5d0abd988815d7e4ce72f47b",
          "md5": "9942ab53f9fa9800bd279a19467d10fd"
        }
      ]
    }
  ]
}
