{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "0.0.1-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.1-snapshot.aar",
          "url": "remote-0.0.1-snapshot.aar",
          "size": 8539,
          "sha512": "232a66255110fa26e59b653f202174aee5f06c985b534b9c74c4e52f609cbb6e66bcac197599458a44d6d6bc0f30e8abbeb777f560d8d9546f40b1279b141cf6",
          "sha256": "e3f5f2e1ddb542672437842f4ca62e79c9ea95a89583290f8d536aff74e1ef6e",
          "sha1": "a129c7e8b60e360d76674d8380650ced1c7c93c1",
          "md5": "6e2201455a452fcdb4be26b251d50fca"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.1-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "0.0.1-snapshot"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.1-snapshot.aar",
          "url": "remote-0.0.1-snapshot.aar",
          "size": 8539,
          "sha512": "232a66255110fa26e59b653f202174aee5f06c985b534b9c74c4e52f609cbb6e66bcac197599458a44d6d6bc0f30e8abbeb777f560d8d9546f40b1279b141cf6",
          "sha256": "e3f5f2e1ddb542672437842f4ca62e79c9ea95a89583290f8d536aff74e1ef6e",
          "sha1": "a129c7e8b60e360d76674d8380650ced1c7c93c1",
          "md5": "6e2201455a452fcdb4be26b251d50fca"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-0.0.1-snapshot-sources.jar",
          "url": "remote-0.0.1-snapshot-sources.jar",
          "size": 7018,
          "sha512": "4f6f519f1cf24239d8af95a34bc6aa1ae211bc0fac303b3701ed4b6b85e3624903d4c6e78d879e44a9ef33efee7aacdc75e674b4bd0e875c679d15eabb3854df",
          "sha256": "397eb324f2bdabe0cebee7860e2a5f2756319fd94ad0368eda29649e75c51c6c",
          "sha1": "1f7cae01ec03e42a19baba6f292671fac4d0f158",
          "md5": "4a10b61cfa427749b3c097607c85ee8f"
        }
      ]
    }
  ]
}
