{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "network",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "network-0.0.1.aar",
          "url": "network-0.0.1.aar",
          "size": 37902,
          "sha512": "7771a4cb5903f2e99f11681fa5eb17ac00749fdfd35aff32d8b232bb305be6a1045494a1f91d5ba4c43b6f3088e14a4d1cc9aa4ba1f7b4446cd77aa0f7d80764",
          "sha256": "f0646e8dfcc180331d0634ffe7331b5f8a00b248a84bba0be9002049fe879eac",
          "sha1": "f1d9c07956c42f2738eb760bcbaacd5c4b1c88d4",
          "md5": "c1b9e1d2348024cd2c01397e502fe06d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "network-0.0.1.aar",
          "url": "network-0.0.1.aar",
          "size": 37902,
          "sha512": "7771a4cb5903f2e99f11681fa5eb17ac00749fdfd35aff32d8b232bb305be6a1045494a1f91d5ba4c43b6f3088e14a4d1cc9aa4ba1f7b4446cd77aa0f7d80764",
          "sha256": "f0646e8dfcc180331d0634ffe7331b5f8a00b248a84bba0be9002049fe879eac",
          "sha1": "f1d9c07956c42f2738eb760bcbaacd5c4b1c88d4",
          "md5": "c1b9e1d2348024cd2c01397e502fe06d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "network-0.0.1-sources.jar",
          "url": "network-0.0.1-sources.jar",
          "size": 22068,
          "sha512": "7e9dc52bbe8e6782c81ae6061bcc0d23b08c2a141c8dd906f1a544ea7fa26e42db58551f156b4866905cf28f8d7b75b4902ca0eecb35512a4f85b7aa6f322b46",
          "sha256": "a24b2ad2e21cba73a471165981ae0eb1842e4088c7906fbe9b2bd977acc74f4b",
          "sha1": "070e44c67b0e0cecc0aa7e241e20a2c2ae1daa42",
          "md5": "11d54833730e1b0b2906e7a497385b10"
        }
      ]
    }
  ]
}
