{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.2.1.aar",
          "url": "data-1.2.1.aar",
          "size": 190190,
          "sha512": "ef9d957f67acec480e0c89cea85ef24fd2b1d9921aab84c165d2ad242f0faa969efcc35a6a016fe10dc522536be99f117c973b4864254b28386d9c045397afb7",
          "sha256": "dc1e4bd246e56101fcaada1633d586916988d0cd19143ddcb2ea839357c23060",
          "sha1": "9cf1432b63c2c8bf308ba545014d3932ffcfe3a0",
          "md5": "58da124d2b905966a6bd0b2629e27442"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.2.1.aar",
          "url": "data-1.2.1.aar",
          "size": 190190,
          "sha512": "ef9d957f67acec480e0c89cea85ef24fd2b1d9921aab84c165d2ad242f0faa969efcc35a6a016fe10dc522536be99f117c973b4864254b28386d9c045397afb7",
          "sha256": "dc1e4bd246e56101fcaada1633d586916988d0cd19143ddcb2ea839357c23060",
          "sha1": "9cf1432b63c2c8bf308ba545014d3932ffcfe3a0",
          "md5": "58da124d2b905966a6bd0b2629e27442"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.2.1-sources.jar",
          "url": "data-1.2.1-sources.jar",
          "size": 21759,
          "sha512": "05f1de7c1c0a35ee028d6b969f5534800daacd917eff46008845070fbb5bd674114a3362f69dc8496a99118467b83fc23ff63c0d2744c037f4d965f368680b0f",
          "sha256": "fbbcb143acaf4f68f52647acefb3c9577995c60525b62ca6182f00ce5ad90560",
          "sha1": "b28be6977fdb10b5122ec495079d0fe74531b289",
          "md5": "0a7d20b9004773ea3d0e52609198d97b"
        }
      ]
    }
  ]
}
