{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.2.1.aar",
          "url": "data-1.2.1.aar",
          "size": 238083,
          "sha512": "6894e8a287049b12e258e7035eb58cccaaa7c2aa287a5ddb77ecdf537096bc54013fb1c3016832603171935c0093d97dde90c397588e5ef5362c8c188ef92233",
          "sha256": "5ef6d8026449aff0ab5217b901521587fca5e45688e718af7851bd4f9bea27c7",
          "sha1": "bb3723247c252845e74c33462931f2aa40f09cf6",
          "md5": "7270e56244271b21943f87fc2eabe8c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.2.1.aar",
          "url": "data-1.2.1.aar",
          "size": 238083,
          "sha512": "6894e8a287049b12e258e7035eb58cccaaa7c2aa287a5ddb77ecdf537096bc54013fb1c3016832603171935c0093d97dde90c397588e5ef5362c8c188ef92233",
          "sha256": "5ef6d8026449aff0ab5217b901521587fca5e45688e718af7851bd4f9bea27c7",
          "sha1": "bb3723247c252845e74c33462931f2aa40f09cf6",
          "md5": "7270e56244271b21943f87fc2eabe8c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.2.1-sources.jar",
          "url": "data-1.2.1-sources.jar",
          "size": 34608,
          "sha512": "7b30fdde0b5ab812fd651137f745f7b6ef2d0e875f0873fa014252b3aefb6c7a108e3907101cb8a594164a71f6b757e3ef37a1c604cb44beb71473776da764b9",
          "sha256": "04afc02d4c1e04a9a648d34d2b7f50d01f68f4af305ce1fe0ab3ab003d3fccb1",
          "sha1": "f25d51b1ce3c8213d99a1d41ff598ab2f388a598",
          "md5": "e75ceb8e7956c54ba8d6739baaaee3e6"
        }
      ]
    }
  ]
}
