{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "0.0.1-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.1-snapshot.aar",
          "url": "designsystem-0.0.1-snapshot.aar",
          "size": 1876376,
          "sha512": "a222e343a4d1fe527d363ea035ff1dcd3389d9b1cfecba2b29ad3a4af4a4e4046c510687138422052c8fe091cb7a325bd9067120aeb70de1c9465d084e8c3470",
          "sha256": "4be34f048e1aa62c4bd0e6840739ab8cfd11232aff699f7bcbabdce8c3c10c15",
          "sha1": "cc5d3b452d15fbbafe62f3887e8cbd232d4dd751",
          "md5": "82e9031f0f59deb1f4d7c3b4d6b01a83"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.1-snapshot.aar",
          "url": "designsystem-0.0.1-snapshot.aar",
          "size": 1876376,
          "sha512": "a222e343a4d1fe527d363ea035ff1dcd3389d9b1cfecba2b29ad3a4af4a4e4046c510687138422052c8fe091cb7a325bd9067120aeb70de1c9465d084e8c3470",
          "sha256": "4be34f048e1aa62c4bd0e6840739ab8cfd11232aff699f7bcbabdce8c3c10c15",
          "sha1": "cc5d3b452d15fbbafe62f3887e8cbd232d4dd751",
          "md5": "82e9031f0f59deb1f4d7c3b4d6b01a83"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "designsystem-0.0.1-snapshot-sources.jar",
          "url": "designsystem-0.0.1-snapshot-sources.jar",
          "size": 41103,
          "sha512": "702433c48af414ac135921b3970b9da43965b47307f4145b4576a0b25a5d45bc4bd5f8206ff8645cd4af1aa4e0a75f1449829869673c099a7af6e7835d7507dc",
          "sha256": "808ebf12cb7322bf856a9fd624cec0dd272bb5ffa735b89f7a435f20d09d3ffb",
          "sha1": "c73ec1f6d7a4d5f222b824aabb9228d989cc3cbb",
          "md5": "40cb081ca746971b4e3d9a7cb082394b"
        }
      ]
    }
  ]
}
