{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.19.aar",
          "url": "domain-0.0.19.aar",
          "size": 132305,
          "sha512": "832145ac3e4fa270e12617e38c347df5329b1d1ca4c76d204d2a2f7bea95788db107f5ba570a827177799a6035dc8ccc4a8964a299e3e88bdbf800ed62409144",
          "sha256": "047f19dacac3180c360799ecd487f185b0baf133284fffa28aecce740abdd1f5",
          "sha1": "87908553c2a4de2533aa9c47ef8013a800564ca8",
          "md5": "e3c8e44bb623926710f6eec11a8ab228"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.19.aar",
          "url": "domain-0.0.19.aar",
          "size": 132305,
          "sha512": "832145ac3e4fa270e12617e38c347df5329b1d1ca4c76d204d2a2f7bea95788db107f5ba570a827177799a6035dc8ccc4a8964a299e3e88bdbf800ed62409144",
          "sha256": "047f19dacac3180c360799ecd487f185b0baf133284fffa28aecce740abdd1f5",
          "sha1": "87908553c2a4de2533aa9c47ef8013a800564ca8",
          "md5": "e3c8e44bb623926710f6eec11a8ab228"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "domain-0.0.19-sources.jar",
          "url": "domain-0.0.19-sources.jar",
          "size": 59398,
          "sha512": "d815aba3da382b2f47fecb5d0fa3aeb956526822025853c7623c72878d606503d5e9e889d47351e75f0da660c81715f331e9b67559e3a1299f2bb13b40e1724f",
          "sha256": "19f14f63fb79dea55cda14e33349de2c726a0fe5c051d4dc3e01af58333ffe1f",
          "sha1": "2680c45d6dbc66a4ecea34de1bdfd2e2be85d077",
          "md5": "b6833e9b9089fcec86d73e4b186c9dd8"
        }
      ]
    }
  ]
}
