{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oitisdk",
    "version": "0.0.14-ofuscated-test-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "data",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.14-ofuscated-test-4.aar",
          "url": "oitisdk-0.0.14-ofuscated-test-4.aar",
          "size": 34374,
          "sha512": "0b6b39e8deeff15be9da326c1f8d30a5f3e94b5f5de8f8fe56f2999bf766913eb1a0e039387d416750daabf599c89f767fdbf8fe08178e2aa39bb8ef80576871",
          "sha256": "f0f42b478ce0fda7c85da887aa3bd8e84d67a2d30254d76dcc69c48069ecada5",
          "sha1": "43b4530f8828a2675da68c496772f2bdaeee968a",
          "md5": "96a4b457c302a815bdbb09fac5acf2c2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "data",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.14-ofuscated-test-4.aar",
          "url": "oitisdk-0.0.14-ofuscated-test-4.aar",
          "size": 34374,
          "sha512": "0b6b39e8deeff15be9da326c1f8d30a5f3e94b5f5de8f8fe56f2999bf766913eb1a0e039387d416750daabf599c89f767fdbf8fe08178e2aa39bb8ef80576871",
          "sha256": "f0f42b478ce0fda7c85da887aa3bd8e84d67a2d30254d76dcc69c48069ecada5",
          "sha1": "43b4530f8828a2675da68c496772f2bdaeee968a",
          "md5": "96a4b457c302a815bdbb09fac5acf2c2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "oitisdk-0.0.14-ofuscated-test-4-sources.jar",
          "url": "oitisdk-0.0.14-ofuscated-test-4-sources.jar",
          "size": 23791,
          "sha512": "68526fbbe1e82339fe005329233a4090d4d76e0220ed62a230a906341c90efad1417c666eabf911092975e272a89cc2156bf391733fb758f65e4bfdc676685c7",
          "sha256": "92e4dd770b31892a6c42ee96b2888bf1eb100ab01cb3d5a87292856c163e8351",
          "sha1": "140f345b928dfd79cf7a7112331dd072744eedb5",
          "md5": "cfa78b01b67024039af8a26c09881fc7"
        }
      ]
    }
  ]
}
