{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.1-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.1-snapshot-1.aar",
          "url": "domain-1.2.1-snapshot-1.aar",
          "size": 156593,
          "sha512": "6c0a95356667f70635a242edf99607e76a977ceb288c8457c184e52afa8d94775794e8b6a3907f6c32b9e1cd317e1c552e67bed69587f97a57a05c1d929a5f21",
          "sha256": "36df3b229ccb8b15e0773c71f33a0c4a9c70a12f133bd4a4977902faa08b04f4",
          "sha1": "600885632c74aa8f7d3d4eb685c0cd6327e2f46d",
          "md5": "0d827a396aeba665c2bd1c24e46d3a26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.1-snapshot-1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.1-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.1-snapshot-1.aar",
          "url": "domain-1.2.1-snapshot-1.aar",
          "size": 156593,
          "sha512": "6c0a95356667f70635a242edf99607e76a977ceb288c8457c184e52afa8d94775794e8b6a3907f6c32b9e1cd317e1c552e67bed69587f97a57a05c1d929a5f21",
          "sha256": "36df3b229ccb8b15e0773c71f33a0c4a9c70a12f133bd4a4977902faa08b04f4",
          "sha1": "600885632c74aa8f7d3d4eb685c0cd6327e2f46d",
          "md5": "0d827a396aeba665c2bd1c24e46d3a26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.1-snapshot-1-sources.jar",
          "url": "domain-1.2.1-snapshot-1-sources.jar",
          "size": 39004,
          "sha512": "3d0b8d3a318bf131bde1257d494ff4dcb20a286c1442e538e11a4f9faba861c2c1dfa33557ac31410841bdcc054eb0e04f7a21758c90d8bcc9874630a4940a39",
          "sha256": "5c476d33167401772574f3bf21f5bf5cac54afe397d5f80140c8a35960bdcb6b",
          "sha1": "b3677675d118044683aec483a1d0b2731eba109c",
          "md5": "3783c5ac0d5307b0b390ce07e006f498"
        }
      ]
    }
  ]
}
