{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oitisdk",
    "version": "0.0.18-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "facetecsdk",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.18-test.aar",
          "url": "oitisdk-0.0.18-test.aar",
          "size": 77690,
          "sha512": "20563c87c1d2771fa6b8416fdac5f593883e452b7187c8209d0f59e592a6b05c6bc99638a37f081f9ddf0b5509b142906568b41bb9c9361e4104dacf0def0a19",
          "sha256": "b7f9ec50952648fe06b8e979782c22753412c23184f93197df22afaa3686ec5e",
          "sha1": "055b5753835aad3acc340f37ae2b0df3a223e255",
          "md5": "856d883d8f5ec009d9cc80e8bae0761e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "data",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "facetecsdk",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.18-test.aar",
          "url": "oitisdk-0.0.18-test.aar",
          "size": 77690,
          "sha512": "20563c87c1d2771fa6b8416fdac5f593883e452b7187c8209d0f59e592a6b05c6bc99638a37f081f9ddf0b5509b142906568b41bb9c9361e4104dacf0def0a19",
          "sha256": "b7f9ec50952648fe06b8e979782c22753412c23184f93197df22afaa3686ec5e",
          "sha1": "055b5753835aad3acc340f37ae2b0df3a223e255",
          "md5": "856d883d8f5ec009d9cc80e8bae0761e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "oitisdk-0.0.18-test-sources.jar",
          "url": "oitisdk-0.0.18-test-sources.jar",
          "size": 37702,
          "sha512": "52c691bbdedff21221980334d907019ea036490feb93c6279a8f83c986e7e377e2818bbde573d68446e02a48aba305f62e55d2eb2ea15b9dae16d7ae05ded5db",
          "sha256": "cefba28fa122c386f9b5749f960f2ffd760e21d6625477ef0d017fdd57336f47",
          "sha1": "02d20fb7b39f614260087163b4f2dc5b22ff6ec6",
          "md5": "ebb2f1ab50330f6a837d4cb48079f21e"
        }
      ]
    }
  ]
}
