{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "core",
    "version": "1.2.1-iproov-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.2.1-iproov-snapshot.aar",
          "url": "core-1.2.1-iproov-snapshot.aar",
          "size": 11049,
          "sha512": "33e2ee19ba371b24a592839fb5746faf457c6bfaf2c5d2a126a30dda04b81af9c56749b262333e10c6a53a2415f8f36d125213115b7b0ab16de93a68d1b0e1fc",
          "sha256": "32444819ad2d6b4cdad27e5fa4e8a0ea7b18094690b4532260edca58706833b3",
          "sha1": "c385281663180ebaccc2fa57bb9a79561b3c7627",
          "md5": "16330423ef8b3706c38d9b4a5ec75626"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.2.1-iproov-snapshot.aar",
          "url": "core-1.2.1-iproov-snapshot.aar",
          "size": 11049,
          "sha512": "33e2ee19ba371b24a592839fb5746faf457c6bfaf2c5d2a126a30dda04b81af9c56749b262333e10c6a53a2415f8f36d125213115b7b0ab16de93a68d1b0e1fc",
          "sha256": "32444819ad2d6b4cdad27e5fa4e8a0ea7b18094690b4532260edca58706833b3",
          "sha1": "c385281663180ebaccc2fa57bb9a79561b3c7627",
          "md5": "16330423ef8b3706c38d9b4a5ec75626"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.2.1-iproov-snapshot-sources.jar",
          "url": "core-1.2.1-iproov-snapshot-sources.jar",
          "size": 4403,
          "sha512": "7de09905611e7ba71821bb20c079ae5f1ae67da77b7d99fd38f6c516edf1349ed59ad1c5cda6bd6b6b45d745bc9063c724c6bd0edff772a269c4516d62127a9b",
          "sha256": "2032b226c93f9ab2d8844700a2fdca0cd9ffbe2dd188c4db2b060c3cbd802fdf",
          "sha1": "b030a4f7b51d344428316fe6535038329d18c3b9",
          "md5": "647aba358c21768fcbe4dc4aeac5962f"
        }
      ]
    }
  ]
}
