{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "0.0.14-ofuscated-test-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.14-ofuscated-test-3.aar",
          "url": "oiti-network-0.0.14-ofuscated-test-3.aar",
          "size": 39213,
          "sha512": "d66faf112cdaa40913363fffd5903df2563a3d68a52574728e0ad6fd6f4d69650e8242cd9138a59540d24f22b80981ff0753075f498a3b745608d17a7db3566a",
          "sha256": "06b4023293a431aced4dbe22be89f18a726913007cd164808593bbdad62b8692",
          "sha1": "be625df4c36131a34a2d0098b05e2ec7ff60156a",
          "md5": "af951b728dafc70af617873b1dfb37c1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.14-ofuscated-test-3.aar",
          "url": "oiti-network-0.0.14-ofuscated-test-3.aar",
          "size": 39213,
          "sha512": "d66faf112cdaa40913363fffd5903df2563a3d68a52574728e0ad6fd6f4d69650e8242cd9138a59540d24f22b80981ff0753075f498a3b745608d17a7db3566a",
          "sha256": "06b4023293a431aced4dbe22be89f18a726913007cd164808593bbdad62b8692",
          "sha1": "be625df4c36131a34a2d0098b05e2ec7ff60156a",
          "md5": "af951b728dafc70af617873b1dfb37c1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "oiti-network-0.0.14-ofuscated-test-3-sources.jar",
          "url": "oiti-network-0.0.14-ofuscated-test-3-sources.jar",
          "size": 22857,
          "sha512": "d8858e4bcb80f5a1f20c1d30e1b272a40c7830f1c574f57f9aab20f28183e1ff0332a7c5ff85fa7382236b2cc6464fc93b2da808bf88e76e7a64e1dcd2ab567e",
          "sha256": "878c1046f86ba2b52816f1399cb7e0b542029cbed2b077b1fbe6ea6dc1c23752",
          "sha1": "19ed5fea66cdf3d4b3026b1d073504bf06014860",
          "md5": "46c18d3d67f28d6dfa2a0f3e77f0585e"
        }
      ]
    }
  ]
}
