{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.1-facetec-v10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.1-facetec-v10.aar",
          "url": "domain-1.2.1-facetec-v10.aar",
          "size": 157853,
          "sha512": "f5cce3c0ba18d34c93f8076d0ec3fbb4647b8eaa048059ac7b36041c3f85cb2df02d67b099edb50ffe37b82aeed70294dbe9a25f142b30fafc9eb06549402aec",
          "sha256": "7dc798a5d11f22da69dfd3d54075cecd6cd5c50bc85d068586a0b85be14d1807",
          "sha1": "aacdd17209e70ba0d29cd1f55265f3da50023609",
          "md5": "8b90b85343fcf38f0978d1ca2c10179d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.1-facetec-v10"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.1-facetec-v10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.1-facetec-v10.aar",
          "url": "domain-1.2.1-facetec-v10.aar",
          "size": 157853,
          "sha512": "f5cce3c0ba18d34c93f8076d0ec3fbb4647b8eaa048059ac7b36041c3f85cb2df02d67b099edb50ffe37b82aeed70294dbe9a25f142b30fafc9eb06549402aec",
          "sha256": "7dc798a5d11f22da69dfd3d54075cecd6cd5c50bc85d068586a0b85be14d1807",
          "sha1": "aacdd17209e70ba0d29cd1f55265f3da50023609",
          "md5": "8b90b85343fcf38f0978d1ca2c10179d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.1-facetec-v10-sources.jar",
          "url": "domain-1.2.1-facetec-v10-sources.jar",
          "size": 39214,
          "sha512": "5d3b81c69aaa1808d16a60eed5033b801e6989f1ee1055222a9cfc466bab125ec640fe47b9eb1d7b5711d954b4955f6277cda13b16c814a52ba13ba7e1f1652c",
          "sha256": "748f6d184dd89ba0946a4eb0052933f4a43c3b841d767c77033f154d14f790fc",
          "sha1": "ea8520e04d53e0e601985789c054bd5798528019",
          "md5": "12c29842222fb0acae6894f22e64aa8d"
        }
      ]
    }
  ]
}
