{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "2.0.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.3-beta.aar",
          "url": "certifacesdk-2.0.3-beta.aar",
          "size": 203173,
          "sha512": "af4c3212cf7d3139f2d2845149e173b3c1d572779a83105111a2491082cb3dfb5a1a1c1ede0e123eee8f410e9d10fcd1bceb00fdbf31348523006771e2e78111",
          "sha256": "0f3b598624893c7b647b5b4bec9c0eee28b7ff1bf52c1b24c64698f952b449bd",
          "sha1": "34854c2eeabd14ae811d63d1703c80edc68cfb7a",
          "md5": "2d539641e594df4e4cbf41be6d41bbf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.3-beta.aar",
          "url": "certifacesdk-2.0.3-beta.aar",
          "size": 203173,
          "sha512": "af4c3212cf7d3139f2d2845149e173b3c1d572779a83105111a2491082cb3dfb5a1a1c1ede0e123eee8f410e9d10fcd1bceb00fdbf31348523006771e2e78111",
          "sha256": "0f3b598624893c7b647b5b4bec9c0eee28b7ff1bf52c1b24c64698f952b449bd",
          "sha1": "34854c2eeabd14ae811d63d1703c80edc68cfb7a",
          "md5": "2d539641e594df4e4cbf41be6d41bbf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-2.0.3-beta-sources.jar",
          "url": "certifacesdk-2.0.3-beta-sources.jar",
          "size": 68794,
          "sha512": "8ddf74d3b3b021579ef8259c9b2c3cdd2d95d5c53c51b6021e0cd3356faaabfe90aeabb4f9acf61c81d1efeb9acaa3354387b10c2d47ba08c4de217e2940aaa7",
          "sha256": "3acc97de63529f46aa15e7bbdd6efc5ea10bfcdcf6480d633a149182908cef81",
          "sha1": "bc2280032c22f046a01407fe63ec216c66a2f0b3",
          "md5": "b6f341abbb25dd2d255416b81af91b07"
        }
      ]
    }
  ]
}
