{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-2.0.1.aar",
          "url": "designsystem-2.0.1.aar",
          "size": 1961445,
          "sha512": "323f5f48a8db52f664d5a278e7ceaa07f73cc25c7bb1164f433be2d7be0533bc04482efb0427d3328f45537d3c7794345c577595e99b74f0bb4043d429a2c5f2",
          "sha256": "de19d4b060d6ac88d5c2e1bc3d8171a2521487fcd226334736a590a1bfcff6df",
          "sha1": "4ad97b8f38671879d3cc07d3e52162b9cfce7756",
          "md5": "d3fa01c06351037ee70e15fdbc429d61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-2.0.1.aar",
          "url": "designsystem-2.0.1.aar",
          "size": 1961445,
          "sha512": "323f5f48a8db52f664d5a278e7ceaa07f73cc25c7bb1164f433be2d7be0533bc04482efb0427d3328f45537d3c7794345c577595e99b74f0bb4043d429a2c5f2",
          "sha256": "de19d4b060d6ac88d5c2e1bc3d8171a2521487fcd226334736a590a1bfcff6df",
          "sha1": "4ad97b8f38671879d3cc07d3e52162b9cfce7756",
          "md5": "d3fa01c06351037ee70e15fdbc429d61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-2.0.1-sources.jar",
          "url": "designsystem-2.0.1-sources.jar",
          "size": 47955,
          "sha512": "de6540c4d53f447dde388e9fb11ccf9f4902379d408f9186a0f72d2fc1eae0075a7d5782bce469c87dc0aeee3564a56fca6254614dd64aa89b3e52e70790b0bd",
          "sha256": "e5272b69ee4c143b0fbb2d120fa48e0ea698e6043dc4fcbdbbd1d64870867b9a",
          "sha1": "9e6ab5e410c541b62839ef16d351a76b938ce752",
          "md5": "a39002ca3d136acdc61e845b651f56ed"
        }
      ]
    }
  ]
}
