{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.2.0.aar",
          "url": "logging-1.2.0.aar",
          "size": 57675,
          "sha512": "c14f03e7fc6163f7921c1837c9a2d4f3272c4a145fc31c8fa7f5c2fe73811efdb8b575b256e5ac0ad1afbaea97274d699feba2999c4869cf69443ca67e2ebbe2",
          "sha256": "b9d896f2875d59ed5c4a3dbd2e53b4dfd27e00b200ad5705752aa89674a30ed5",
          "sha1": "fa46093c059b98d8261d6a97fe8da8a501258478",
          "md5": "f9f221c300f0c4e924307b68c0849775"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.2.0.aar",
          "url": "logging-1.2.0.aar",
          "size": 57675,
          "sha512": "c14f03e7fc6163f7921c1837c9a2d4f3272c4a145fc31c8fa7f5c2fe73811efdb8b575b256e5ac0ad1afbaea97274d699feba2999c4869cf69443ca67e2ebbe2",
          "sha256": "b9d896f2875d59ed5c4a3dbd2e53b4dfd27e00b200ad5705752aa89674a30ed5",
          "sha1": "fa46093c059b98d8261d6a97fe8da8a501258478",
          "md5": "f9f221c300f0c4e924307b68c0849775"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.2.0-sources.jar",
          "url": "logging-1.2.0-sources.jar",
          "size": 24627,
          "sha512": "77a12538121da83131c9648b3a489549ecaa059f3d81dc65552ba718bb23304d7b8572d7a190066addf0ec22c5cf221240f143e920055b7cc2cfeea0241cf1e1",
          "sha256": "aa03a624a0ec0a17cd520448cd0a6474008dd1f8a5365dae9f51356b4a32999a",
          "sha1": "129c13da31535dbf5668885a839f69d0a1743c18",
          "md5": "d6a8b01bbb0a822aac3c50a7edb768ec"
        }
      ]
    }
  ]
}
