{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "0.0.14-ofuscated-test-8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-8.aar",
          "url": "utils-0.0.14-ofuscated-test-8.aar",
          "size": 65256,
          "sha512": "4d161093346dc116e3f444db8825baf470e19ef74f6c62582c1634561f03e44e5b613980a95b14e569a5d8d3924e206f2c82ed4e32e3f922946e1ada1152efd6",
          "sha256": "333c7a4a5e3697bf61f71965256fdaa5feed4c074c1b592bdffde45b64489077",
          "sha1": "8836f5a47d6ed62e8330721665767d7eea3b364a",
          "md5": "e4de0d8fb423f471facfe1f2562b21d4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-8.aar",
          "url": "utils-0.0.14-ofuscated-test-8.aar",
          "size": 65256,
          "sha512": "4d161093346dc116e3f444db8825baf470e19ef74f6c62582c1634561f03e44e5b613980a95b14e569a5d8d3924e206f2c82ed4e32e3f922946e1ada1152efd6",
          "sha256": "333c7a4a5e3697bf61f71965256fdaa5feed4c074c1b592bdffde45b64489077",
          "sha1": "8836f5a47d6ed62e8330721665767d7eea3b364a",
          "md5": "e4de0d8fb423f471facfe1f2562b21d4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-8-sources.jar",
          "url": "utils-0.0.14-ofuscated-test-8-sources.jar",
          "size": 36092,
          "sha512": "d60d9262d6158015caf268877ae5e27e4e97145299ebcaf9c57f54fc66319501523b3ac477e9e7ac5d6dfa0d2e4c7dc2b741ed9a511dd3e3a27e5b106d7bed3b",
          "sha256": "be30a960e15196cceb649cd5a68900d38bf6c00dddda7828dba837effc7ecf57",
          "sha1": "ae40adec58ebb0578ed88ce365595254f129dbae",
          "md5": "d1f98631b6073b34cca64574e509abd2"
        }
      ]
    }
  ]
}
