{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "remote",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.2.1.aar",
          "url": "remote-1.2.1.aar",
          "size": 49384,
          "sha512": "20d72aaa3a1fb91c2de9611201283f3b06c01a8f887a90499c9d972f6a9022d92591bee6bc977d1b68d386cf88e36c7b5a557f85c0029c4546f547e7c8bf8031",
          "sha256": "7f0c5c05a7fd89aad7471cefd5f2eff52d9e83b3f592efc6f9185bde3d696b8a",
          "sha1": "7a569fcb35c3ec606f48e7d43a6a833764769a94",
          "md5": "6f6abee6046acab623d3d7350b64fb12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.2.1.aar",
          "url": "remote-1.2.1.aar",
          "size": 49384,
          "sha512": "20d72aaa3a1fb91c2de9611201283f3b06c01a8f887a90499c9d972f6a9022d92591bee6bc977d1b68d386cf88e36c7b5a557f85c0029c4546f547e7c8bf8031",
          "sha256": "7f0c5c05a7fd89aad7471cefd5f2eff52d9e83b3f592efc6f9185bde3d696b8a",
          "sha1": "7a569fcb35c3ec606f48e7d43a6a833764769a94",
          "md5": "6f6abee6046acab623d3d7350b64fb12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-1.2.1-sources.jar",
          "url": "remote-1.2.1-sources.jar",
          "size": 9606,
          "sha512": "47ee88b4fc929e9e92b600270b6e17f7d027786c99d5196d77f456e7080e6de1ff6dc82ca14ac7eba12b25eae40988ed1e9a18fa1c0f67553b93b83149ada8c4",
          "sha256": "384078452e678caed7124875f6e7a5080b98c514ba9eba16b59d9751aad693fe",
          "sha1": "e0ebe559cc528bc88865a1587cd4be83c640279b",
          "md5": "fb7f60b1ac72d50c613426df68def30c"
        }
      ]
    }
  ]
}
