{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.14.aar",
          "url": "core-0.0.14.aar",
          "size": 10375,
          "sha512": "2c18364b85f40a2b3984d31f6cbdbbad05020252367dcb8a1a5167b4c62da009f22aec2d5d491bd23ee09920609091825ebf7117b3be1b791c349cc083986cca",
          "sha256": "1183d078d36da964b2b1b85815b270bbe4f8ff9459ef751ad731570d0cde1044",
          "sha1": "91c722ec8d38aeec5fdb423cccfe436a353c6245",
          "md5": "57285e555a60d419d6aab6d5548c11c5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.14.aar",
          "url": "core-0.0.14.aar",
          "size": 10375,
          "sha512": "2c18364b85f40a2b3984d31f6cbdbbad05020252367dcb8a1a5167b4c62da009f22aec2d5d491bd23ee09920609091825ebf7117b3be1b791c349cc083986cca",
          "sha256": "1183d078d36da964b2b1b85815b270bbe4f8ff9459ef751ad731570d0cde1044",
          "sha1": "91c722ec8d38aeec5fdb423cccfe436a353c6245",
          "md5": "57285e555a60d419d6aab6d5548c11c5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.0.14-sources.jar",
          "url": "core-0.0.14-sources.jar",
          "size": 6741,
          "sha512": "cf48b10561b2309a6befbf4ef31848ede432b7e48c2fe74972762286d9567362e3096be91a8ec4a4d58ca1a38fd2159f22a5d7780a10a3c162a2183983bf276d",
          "sha256": "096132eefc5b522162971096d3cffd3b6c3fb236c9776fd635e621faef71e0a4",
          "sha1": "a53afefebdf2165548ef9a6534b409720906763f",
          "md5": "7de6f8db6cb704234fe43e492cd11614"
        }
      ]
    }
  ]
}
