{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0-snapshot-3.aar",
          "url": "domain-1.2.0-snapshot-3.aar",
          "size": 162939,
          "sha512": "49f2d16496d1180e1295fff1693ad5957fed2a381323015ffc39cf72639c3c75718ebae856dad79e73ee53d225d3f3fefdb476a407702a1fd5e4d778b0568dfe",
          "sha256": "7a63d0157afa1561b4c5a45de0e098641f37c382fe78ad6370945e0a91804eee",
          "sha1": "9e5c3e2c59cf8d785053599c6b53de234a904b7e",
          "md5": "37c5631676c5dd36c29dfb5682d0e295"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.0-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0-snapshot-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0-snapshot-3.aar",
          "url": "domain-1.2.0-snapshot-3.aar",
          "size": 162939,
          "sha512": "49f2d16496d1180e1295fff1693ad5957fed2a381323015ffc39cf72639c3c75718ebae856dad79e73ee53d225d3f3fefdb476a407702a1fd5e4d778b0568dfe",
          "sha256": "7a63d0157afa1561b4c5a45de0e098641f37c382fe78ad6370945e0a91804eee",
          "sha1": "9e5c3e2c59cf8d785053599c6b53de234a904b7e",
          "md5": "37c5631676c5dd36c29dfb5682d0e295"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.0-snapshot-3-sources.jar",
          "url": "domain-1.2.0-snapshot-3-sources.jar",
          "size": 40746,
          "sha512": "eae7cc685ebf2ba09cecd6a1239316bb3dc95e455d7a3abd08cdebd9652b2e810930a2d5bf5ef916f063ce1cea292fcbcc75bd3b4f3a744f1c6536f882214353",
          "sha256": "e1c9a164ceda122c1983b612d0790165a1aa4e4258588abcb383c751758fe126",
          "sha1": "2a48836eb181bc6941ba3b6875e3645b16fdc41e",
          "md5": "d7f14565808b28687cf98c0ace129647"
        }
      ]
    }
  ]
}
