{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "1.3.1-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.3.1-snapshot-3.aar",
          "url": "data-1.3.1-snapshot-3.aar",
          "size": 236670,
          "sha512": "b4dbf0ba62ccdb0dcd4da97ea06d44419d10925cd129861af430153c8190fa33ffdc34dd1df8eea98e52d6ccc6b285c29cc48712519e4be59a41776458263bae",
          "sha256": "cf2d969dc126539988e8e5368e565b21766e8d8e5f843ca2ecb54732d81932d1",
          "sha1": "494f07398b47be2e8b90427cfcf1e22d38eefc4e",
          "md5": "dd4dbb147546f9605e107c37dbe27efa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.3.1-snapshot-3.aar",
          "url": "data-1.3.1-snapshot-3.aar",
          "size": 236670,
          "sha512": "b4dbf0ba62ccdb0dcd4da97ea06d44419d10925cd129861af430153c8190fa33ffdc34dd1df8eea98e52d6ccc6b285c29cc48712519e4be59a41776458263bae",
          "sha256": "cf2d969dc126539988e8e5368e565b21766e8d8e5f843ca2ecb54732d81932d1",
          "sha1": "494f07398b47be2e8b90427cfcf1e22d38eefc4e",
          "md5": "dd4dbb147546f9605e107c37dbe27efa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.3.1-snapshot-3-sources.jar",
          "url": "data-1.3.1-snapshot-3-sources.jar",
          "size": 34548,
          "sha512": "e195821b5122a790aea3f7bc8ac48eb12dede33b1aa886b7428dc1b61b7243b6532b89dc83fe3f4e6c3a22e30974736f3ef1832cc503eb324315e4db1649d05a",
          "sha256": "dceb6bd8b1ea12ceeb18b60431685228b8efe9b0798e542a26a86df14ee9e400",
          "sha1": "115dbea132ded88cdf514e966e8851ea96b9761a",
          "md5": "1f6c1084af86cc2e0b94a6a1127893ec"
        }
      ]
    }
  ]
}
