{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "di",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.2.1.aar",
          "url": "di-1.2.1.aar",
          "size": 1761,
          "sha512": "dda390022de4c6ef0b649a1ac5cf7f029e9c2013415e243a02b53677968deec4466fe82f4d780689da9776ef155de36e98106a59b5d9085637f9dd6aed3d22d2",
          "sha256": "2d76f4ba740ceaed426e86a3c5a68ee06404e32f02d6e7694c724e663f7be90f",
          "sha1": "4f6ce7b0fef905b94800894c124f716880f6bc2e",
          "md5": "b18d446fd865da5dab1c3b34d148607a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.2.1.aar",
          "url": "di-1.2.1.aar",
          "size": 1761,
          "sha512": "dda390022de4c6ef0b649a1ac5cf7f029e9c2013415e243a02b53677968deec4466fe82f4d780689da9776ef155de36e98106a59b5d9085637f9dd6aed3d22d2",
          "sha256": "2d76f4ba740ceaed426e86a3c5a68ee06404e32f02d6e7694c724e663f7be90f",
          "sha1": "4f6ce7b0fef905b94800894c124f716880f6bc2e",
          "md5": "b18d446fd865da5dab1c3b34d148607a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "di-1.2.1-sources.jar",
          "url": "di-1.2.1-sources.jar",
          "size": 927,
          "sha512": "7bed627e543fcf773e1e1ea5672086f3b45e48f53200e7118c1b7143b5e3fc8da02b2cc2bdd7e38d2209023f45e2f20c39efb9878ae469afe38f30d3c6ebe30c",
          "sha256": "57662065f7918baa8104f68a912559b7522db869409f098b6784d3f8f7080870",
          "sha1": "fc0264376a68940e3d364557694aa4b5df73c4e5",
          "md5": "34c61e277cbedac03512078cedce4ecb"
        }
      ]
    }
  ]
}
