{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "network",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.2.0.aar",
          "url": "network-1.2.0.aar",
          "size": 27611,
          "sha512": "58e77507f929fd39c7386dd86316f0f06294b0b0861a1b7913619b759d346978f80d9f5c2560e1d9b0a7be90888d95f7fe2afffd03033faf47db68b4c507d5d7",
          "sha256": "e3d63d3bdc19079e52cd1ad22194f99b35d0dad4084c17cdf3c0b8cad5169deb",
          "sha1": "4e6a203f89123d22db8d2412764c6a6d9ba6eb3d",
          "md5": "5a883eda63084956a024a4900f88f785"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.2.0.aar",
          "url": "network-1.2.0.aar",
          "size": 27611,
          "sha512": "58e77507f929fd39c7386dd86316f0f06294b0b0861a1b7913619b759d346978f80d9f5c2560e1d9b0a7be90888d95f7fe2afffd03033faf47db68b4c507d5d7",
          "sha256": "e3d63d3bdc19079e52cd1ad22194f99b35d0dad4084c17cdf3c0b8cad5169deb",
          "sha1": "4e6a203f89123d22db8d2412764c6a6d9ba6eb3d",
          "md5": "5a883eda63084956a024a4900f88f785"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "network-1.2.0-sources.jar",
          "url": "network-1.2.0-sources.jar",
          "size": 14768,
          "sha512": "771572c37b5d598e18935b50b6e73e8f31bd4a81bcb99417410720f3ab9b407ebac74301c5113bd2e7da34f6c65e71f18091520704da6cf81d9bbf3e081b450e",
          "sha256": "a9d25bf728e11bed0b294acf272d7ed1f52f4dadbe8cd52e8f0a5aa4ebc0b5a5",
          "sha1": "2e87f8f3345df255a4b614d88d12a202ae3e3ce3",
          "md5": "d4f426871c920d78d33237a8b02b563a"
        }
      ]
    }
  ]
}
