{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "di",
    "version": "0.0.14-ofuscated-test-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "di-0.0.14-ofuscated-test-3.aar",
          "url": "di-0.0.14-ofuscated-test-3.aar",
          "size": 1750,
          "sha512": "5d680c01dc732439c433b2089533b9d1b6dfa862b1e6c23246bc7f5c739e6426e9ea6d898773d162d4984fd0b5f5b2b63f67082efc9726a53937c3bbd4c6a45b",
          "sha256": "8a57d75428037e69cb1a3b8372bcfd08abf012ef1c10ac5b2fff7ef0a959fabf",
          "sha1": "2ae15443cccb383762f34e9b5d4c21c7c1720ea3",
          "md5": "8edc88ae5d19394ba0388c9fdd2df512"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "di-0.0.14-ofuscated-test-3.aar",
          "url": "di-0.0.14-ofuscated-test-3.aar",
          "size": 1750,
          "sha512": "5d680c01dc732439c433b2089533b9d1b6dfa862b1e6c23246bc7f5c739e6426e9ea6d898773d162d4984fd0b5f5b2b63f67082efc9726a53937c3bbd4c6a45b",
          "sha256": "8a57d75428037e69cb1a3b8372bcfd08abf012ef1c10ac5b2fff7ef0a959fabf",
          "sha1": "2ae15443cccb383762f34e9b5d4c21c7c1720ea3",
          "md5": "8edc88ae5d19394ba0388c9fdd2df512"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "di-0.0.14-ofuscated-test-3-sources.jar",
          "url": "di-0.0.14-ofuscated-test-3-sources.jar",
          "size": 1291,
          "sha512": "b8e8b2520537ffdb50067514844716c0a7ede29a10d356781f896b8d5d6588bf5f60550d47f8aa1baa65a2559e11b8d8047972aaba087c98576436fc43983437",
          "sha256": "453b819052d8993c888103898c18fdd327bde816e75aed0d16e926ad4821dd3c",
          "sha1": "3e195307ebfd9beaa38790541ac163e4e9e1bde2",
          "md5": "1767a2b3ddf43d85de29efeefcea33e0"
        }
      ]
    }
  ]
}
