{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "core",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.0.0.aar",
          "url": "core-2.0.0.aar",
          "size": 12404,
          "sha512": "35fd6fa11f8d301695f8667f1b9d3ac310f390e995e783bdff11c436a8c0c053562dcc1cf643f774aa20dafc48d90b9886ff3e862bd78f2ef389576acc82f29c",
          "sha256": "c64f4df17ea58c02da8aeb591f34034f9a363e419aba914534d151dc078b59ca",
          "sha1": "8f95d63a256b2143c6a47bce85b3761c198f0ff9",
          "md5": "43f49c6cbb324a1dc52d4a16f8c30800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.0.0.aar",
          "url": "core-2.0.0.aar",
          "size": 12404,
          "sha512": "35fd6fa11f8d301695f8667f1b9d3ac310f390e995e783bdff11c436a8c0c053562dcc1cf643f774aa20dafc48d90b9886ff3e862bd78f2ef389576acc82f29c",
          "sha256": "c64f4df17ea58c02da8aeb591f34034f9a363e419aba914534d151dc078b59ca",
          "sha1": "8f95d63a256b2143c6a47bce85b3761c198f0ff9",
          "md5": "43f49c6cbb324a1dc52d4a16f8c30800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-2.0.0-sources.jar",
          "url": "core-2.0.0-sources.jar",
          "size": 4874,
          "sha512": "18ebb6222745370645284477b3e8394aace3e1c46160e992836f6be0a70f648b8142e4ced0935efd07ea9be1f7bdaf0f6df58cd010df18466d3fea20a9a37136",
          "sha256": "a3f2b26f29135dc422f2bc336eabc9138c538ae2f0fafa96489ea471bab9e614",
          "sha1": "26df72e62c67e89f082021a61c997415064bea2f",
          "md5": "999ccab0ae63e8db66281c5e34d1899e"
        }
      ]
    }
  ]
}
