{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "2.0.4-beta-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.4-beta-2.aar",
          "url": "data-2.0.4-beta-2.aar",
          "size": 235818,
          "sha512": "d53869eb986036d7972184e76ddcb5e16d8fadde6855037b80b863a7a59d78b80b9d64f87eea1c10915f45bbf0c5371aee0f56aff44be9055db08bacfa4cec0e",
          "sha256": "771e7b3e080f45bb55f237978f2c1acc1332cf11e9d5162679239d781e2c95e8",
          "sha1": "d0b4667318e07bcd5914f80fc6c0a7ca0ef70256",
          "md5": "e1d6892b418d8c32e1645ead9e1efb15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.4-beta-2.aar",
          "url": "data-2.0.4-beta-2.aar",
          "size": 235818,
          "sha512": "d53869eb986036d7972184e76ddcb5e16d8fadde6855037b80b863a7a59d78b80b9d64f87eea1c10915f45bbf0c5371aee0f56aff44be9055db08bacfa4cec0e",
          "sha256": "771e7b3e080f45bb55f237978f2c1acc1332cf11e9d5162679239d781e2c95e8",
          "sha1": "d0b4667318e07bcd5914f80fc6c0a7ca0ef70256",
          "md5": "e1d6892b418d8c32e1645ead9e1efb15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-2.0.4-beta-2-sources.jar",
          "url": "data-2.0.4-beta-2-sources.jar",
          "size": 34557,
          "sha512": "9b49bd6c6019dd0dd94fa595ade584a7acf21b7a134abc25aa86f0fd0258e0159871312b0765d3b932e13b47d9b97b819664c10b8175503feb1de440bce5c7df",
          "sha256": "0e2a10a85cc1c10dad8c7fe0d7e585fca37bf7566dabeb78fce139b76504e31b",
          "sha1": "4eea01c1eaa7e8165f71ddb36a737a03cb33e542",
          "md5": "650352e9b470bbe3f2c8aa91e6c080d6"
        }
      ]
    }
  ]
}
