{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "0.0.14-ofuscated-test-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.14-ofuscated-test-2.aar",
          "url": "remote-0.0.14-ofuscated-test-2.aar",
          "size": 9014,
          "sha512": "20df983090ae95e56820818ab6df322898224b22a30c674749a76dcbb342d627f0cf360fd26331c84cb65884580d6c68c10715838047bd675d71358edb52a341",
          "sha256": "d6133084b3b7b4d4886c4094b7a9626515b404a2e941aa70aa3ba42448a3bb81",
          "sha1": "8171d6bb699c0741b44d79b936094b13a2a579aa",
          "md5": "55cd764a0187b829d9382105e08e8a55"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.14-ofuscated-test-2"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.14-ofuscated-test-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.14-ofuscated-test-2.aar",
          "url": "remote-0.0.14-ofuscated-test-2.aar",
          "size": 9014,
          "sha512": "20df983090ae95e56820818ab6df322898224b22a30c674749a76dcbb342d627f0cf360fd26331c84cb65884580d6c68c10715838047bd675d71358edb52a341",
          "sha256": "d6133084b3b7b4d4886c4094b7a9626515b404a2e941aa70aa3ba42448a3bb81",
          "sha1": "8171d6bb699c0741b44d79b936094b13a2a579aa",
          "md5": "55cd764a0187b829d9382105e08e8a55"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-0.0.14-ofuscated-test-2-sources.jar",
          "url": "remote-0.0.14-ofuscated-test-2-sources.jar",
          "size": 7196,
          "sha512": "31e96f744bc178d06f225271ab64415e215718f0f6282da2ea0fdb30aed65c414f286b1c51d80fa5efe2f1a9523fbeb9667ac3241f1ee496a4a576764992f83d",
          "sha256": "f5c2979507b479321336e4423a05e731d2d0f54d5c70f132937f170ca36bd77b",
          "sha1": "6524fc31246ef465f74e8bf1ac3ad46cdbf36eea",
          "md5": "90081d5349fa354e5428c4101226f107"
        }
      ]
    }
  ]
}
