{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.3.0.aar",
          "url": "domain-1.3.0.aar",
          "size": 218125,
          "sha512": "0b714b92304ea0b8319df8f9cd18b10063288c32c8312502d48ff9e3dc46f2b12863fc12a404f835cf66e8ed822ba4e461c27450786d86e3e15e229668b126d0",
          "sha256": "ef78e37f85036ca74f2513191625cf2ba963b2778a720daa9ae1b7559302a9d0",
          "sha1": "aafaac1d42faefcfd191e5235af4171f4bc4097d",
          "md5": "aa9db79e1025d78199de8e6dd810a23e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.3.0.aar",
          "url": "domain-1.3.0.aar",
          "size": 218125,
          "sha512": "0b714b92304ea0b8319df8f9cd18b10063288c32c8312502d48ff9e3dc46f2b12863fc12a404f835cf66e8ed822ba4e461c27450786d86e3e15e229668b126d0",
          "sha256": "ef78e37f85036ca74f2513191625cf2ba963b2778a720daa9ae1b7559302a9d0",
          "sha1": "aafaac1d42faefcfd191e5235af4171f4bc4097d",
          "md5": "aa9db79e1025d78199de8e6dd810a23e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.3.0-sources.jar",
          "url": "domain-1.3.0-sources.jar",
          "size": 55645,
          "sha512": "acafe7d8ebbf5c1404a61b167de5041bebfb613725fc0eae5840082ebdeb00f7f967bf7894f4637774bb0817f8ed02e65e74b74316b2492430916feaa5b91313",
          "sha256": "4c98a54f3ce639a9b1ae3508a192c4f51dd5f9c4749bf65aa6f89db68010b700",
          "sha1": "370babce40a1179d4e68c32640321d21fb027872",
          "md5": "1fa4dbb1f9d597f1d9920bc50f71ab2a"
        }
      ]
    }
  ]
}
