{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "facetecsdk",
    "version": "2.0.0-beta-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.135"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-2.0.0-beta-3.aar",
          "url": "facetecsdk-2.0.0-beta-3.aar",
          "size": 589103,
          "sha512": "5971ce822f71595fb8b6acca8e7b1a9c8df685933c8569a311719a835f092e440217bc4715ef9e0801612bea759de690112521e5c150ce6dd4885805abadfa94",
          "sha256": "09df9bb9c94db4fb5b4f505d29fcfdb0451a8ea981e82e0b5fd38f5041ec16e4",
          "sha1": "00a5932cc51f52bb8d3de607558d809e2711c93d",
          "md5": "ada42527be035e5070004ede030221ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.135"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-2.0.0-beta-3.aar",
          "url": "facetecsdk-2.0.0-beta-3.aar",
          "size": 589103,
          "sha512": "5971ce822f71595fb8b6acca8e7b1a9c8df685933c8569a311719a835f092e440217bc4715ef9e0801612bea759de690112521e5c150ce6dd4885805abadfa94",
          "sha256": "09df9bb9c94db4fb5b4f505d29fcfdb0451a8ea981e82e0b5fd38f5041ec16e4",
          "sha1": "00a5932cc51f52bb8d3de607558d809e2711c93d",
          "md5": "ada42527be035e5070004ede030221ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "facetecsdk-2.0.0-beta-3-sources.jar",
          "url": "facetecsdk-2.0.0-beta-3-sources.jar",
          "size": 110384,
          "sha512": "137cb654aa1f4cf90ec2009a77c254f1e4650775dcf9adf08d9d9f97e704d281c5d3a1047ea9aaebea957d84f849c7954212c1c9c62be16f44f5a47932cf62cd",
          "sha256": "e402e8fd923d8101ebe5717823b3a80c0491453303e84d2f874ac556a370f54d",
          "sha1": "dfe1708f9e8ce20fed79c0e34afa0933ca3751ba",
          "md5": "b460f9ddb0a3fd1178a84597dc0a7188"
        }
      ]
    }
  ]
}
