{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "1.2.1-iproov-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-1.2.1-iproov-snapshot.aar",
          "url": "certifacesdk-1.2.1-iproov-snapshot.aar",
          "size": 94508,
          "sha512": "8f6af25fc00b39479467202c795008bcf592b4b7d801e17a05bf322cc653bbecd83f1c531d52d0df1902d0eb2859f3bcf395b6c26917ad851790ebab01d5460f",
          "sha256": "c812afc59e5ccde072be0d9117d60aa4707d7575174fb7ec6c183818f69a7fae",
          "sha1": "df25c62ccf46cd3280ea5228e19b3ae48fd86f58",
          "md5": "26c346a2de2fb6472b86720c3151902f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "certiface-network",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "1.2.1-iproov-snapshot"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-1.2.1-iproov-snapshot.aar",
          "url": "certifacesdk-1.2.1-iproov-snapshot.aar",
          "size": 94508,
          "sha512": "8f6af25fc00b39479467202c795008bcf592b4b7d801e17a05bf322cc653bbecd83f1c531d52d0df1902d0eb2859f3bcf395b6c26917ad851790ebab01d5460f",
          "sha256": "c812afc59e5ccde072be0d9117d60aa4707d7575174fb7ec6c183818f69a7fae",
          "sha1": "df25c62ccf46cd3280ea5228e19b3ae48fd86f58",
          "md5": "26c346a2de2fb6472b86720c3151902f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-1.2.1-iproov-snapshot-sources.jar",
          "url": "certifacesdk-1.2.1-iproov-snapshot-sources.jar",
          "size": 38219,
          "sha512": "d91d693e8f1d11b75e295b7df502ae330285567f55186e4c1c9cf5cc3e2fb109c042651ad70f56f666ab684d2909137aac585af898134e911a01a4c2326f1d48",
          "sha256": "6af7c268a2ec8eb62416bd47596b52713656233d16b6c02240c51f6a5a687c65",
          "sha1": "121291dbd539effeb00565718502b512874d54dc",
          "md5": "0687076a57c14c3602e392176e2f650c"
        }
      ]
    }
  ]
}
