{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.18.aar",
          "url": "logging-0.0.18.aar",
          "size": 33905,
          "sha512": "f812b2ffad0df44e47c88d1b190e3c99eefcaacc87a8e13e5a15d81ea92612c980332ae436a81e731a08bb92524da0e5a0d5cfcc9acd42f35f6f5eabeaf33ff2",
          "sha256": "e2dafc6ddf8d3176b64f54410787c54edc6f51211c2abe3d4a2b0bb266968816",
          "sha1": "8adf46d7b9d4f9e089813983032b019ab9011a2e",
          "md5": "5f84cc1486da41739590f67affc5684f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.18"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.18.aar",
          "url": "logging-0.0.18.aar",
          "size": 33905,
          "sha512": "f812b2ffad0df44e47c88d1b190e3c99eefcaacc87a8e13e5a15d81ea92612c980332ae436a81e731a08bb92524da0e5a0d5cfcc9acd42f35f6f5eabeaf33ff2",
          "sha256": "e2dafc6ddf8d3176b64f54410787c54edc6f51211c2abe3d4a2b0bb266968816",
          "sha1": "8adf46d7b9d4f9e089813983032b019ab9011a2e",
          "md5": "5f84cc1486da41739590f67affc5684f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logging-0.0.18-sources.jar",
          "url": "logging-0.0.18-sources.jar",
          "size": 20013,
          "sha512": "2e19ee91ebcbfdbbfb569a4216c7cdd3cd09b240b79b963cc4871bfcf6301210600ea7f7f56b2fb9466d1594a8c78346c981fac8f6aa45bdee6633d2eb773199",
          "sha256": "2ea17933a790b685e9f089b8e85810b252b567d75f9738a1c75cddc072073328",
          "sha1": "a71bb29cbe642aec4e7aa4ff3bc97ccc1a1c805a",
          "md5": "28166619a4ca1982214d2d618391e029"
        }
      ]
    }
  ]
}
