{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.0.aar",
          "url": "data-2.0.0.aar",
          "size": 187807,
          "sha512": "0bc18dd301f8a9e12fc44830d76378aeffafc26a8ed87cc38a731bcf3e003f4b6c616a17c953f91adf9323394b0804734cc8822c1f395dea93dc324993fcc4f5",
          "sha256": "14f0c09098b05890199d96ca9f7287b7f2abb61aee62c295f89ca04f3e2a095e",
          "sha1": "8183da227c2b2dda33aa2e74f8621236a0f31312",
          "md5": "57460d85aa7c90505ffe49f97100fc7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.0.aar",
          "url": "data-2.0.0.aar",
          "size": 187807,
          "sha512": "0bc18dd301f8a9e12fc44830d76378aeffafc26a8ed87cc38a731bcf3e003f4b6c616a17c953f91adf9323394b0804734cc8822c1f395dea93dc324993fcc4f5",
          "sha256": "14f0c09098b05890199d96ca9f7287b7f2abb61aee62c295f89ca04f3e2a095e",
          "sha1": "8183da227c2b2dda33aa2e74f8621236a0f31312",
          "md5": "57460d85aa7c90505ffe49f97100fc7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-2.0.0-sources.jar",
          "url": "data-2.0.0-sources.jar",
          "size": 19658,
          "sha512": "38f3e6db06c159ce411192e40d8aaf467b36366628abf1cdc7b59560251598e51c9e3620be532de2e4a5c0f5bec0b1cbb4410090755aef25f03bd52ee4fd9635",
          "sha256": "fef3fc30fb67b028ef5189a418dc905015020888120b29a692be0408689bc453",
          "sha1": "0369d9652f3bc162a2d32649ac16398850be7ec3",
          "md5": "781cea9fd4fceb2874b749d55e1bc18f"
        }
      ]
    }
  ]
}
