{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.0.aar",
          "url": "data-2.0.0.aar",
          "size": 237437,
          "sha512": "c57598d2890a9f23c87f8d6ab053e79ceb9ebfdc2d71f880182f4417a2a036d772ee1d9a1f8a8ec33bb62fb7618b2c9a7d7c63b85e4d358a6b7d88e755fead43",
          "sha256": "aac31e5dd4080089b0bfea6ade9273237df509f0f7c7b1b089379f23711ab1dc",
          "sha1": "aefee9a129cbeaa4569bd7f85a4009c5881f5044",
          "md5": "fa6230f8aff41859269cf21da041034b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.0.aar",
          "url": "data-2.0.0.aar",
          "size": 237437,
          "sha512": "c57598d2890a9f23c87f8d6ab053e79ceb9ebfdc2d71f880182f4417a2a036d772ee1d9a1f8a8ec33bb62fb7618b2c9a7d7c63b85e4d358a6b7d88e755fead43",
          "sha256": "aac31e5dd4080089b0bfea6ade9273237df509f0f7c7b1b089379f23711ab1dc",
          "sha1": "aefee9a129cbeaa4569bd7f85a4009c5881f5044",
          "md5": "fa6230f8aff41859269cf21da041034b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-2.0.0-sources.jar",
          "url": "data-2.0.0-sources.jar",
          "size": 34792,
          "sha512": "55bf4018a33a7e0df64dfa9349673e3d90718b45a0a4a4f512b108e52c7c6d9c6f17399c6aebb7b95dae43ddf5455ddcb2998617969613bb8a58d3f017f78774",
          "sha256": "8b9ac5105e89551706b9d6a2bbe93731fcbba582b43a562439a006d6436af538",
          "sha1": "6e6baa0d6cfd39be95a12562f5fad4c109369c16",
          "md5": "5b17d33db8fc021483bae25d70b5e3aa"
        }
      ]
    }
  ]
}
