{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oitisdk",
    "version": "0.0.14-ofuscated-test-6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.14-ofuscated-test-6.aar",
          "url": "oitisdk-0.0.14-ofuscated-test-6.aar",
          "size": 34579,
          "sha512": "d096ec1295c1a874c12ecff153a25d3b0ff0bba3166ece842be90cc6839d1aa72c6191bffc1ce8bcc2e04aa53e2419fc18a45d4c18f719666e3cf5f9b87ea9b1",
          "sha256": "f41d6ed38e36414de9df94c9ecf0b4508e5829e6741a8f34f357946f39dcbea1",
          "sha1": "b0b4d927ee3568d2afa387560221971ab903868d",
          "md5": "0714d9e408612fd75e7e8c6596954053"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "data",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.14-ofuscated-test-6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.14-ofuscated-test-6.aar",
          "url": "oitisdk-0.0.14-ofuscated-test-6.aar",
          "size": 34579,
          "sha512": "d096ec1295c1a874c12ecff153a25d3b0ff0bba3166ece842be90cc6839d1aa72c6191bffc1ce8bcc2e04aa53e2419fc18a45d4c18f719666e3cf5f9b87ea9b1",
          "sha256": "f41d6ed38e36414de9df94c9ecf0b4508e5829e6741a8f34f357946f39dcbea1",
          "sha1": "b0b4d927ee3568d2afa387560221971ab903868d",
          "md5": "0714d9e408612fd75e7e8c6596954053"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "oitisdk-0.0.14-ofuscated-test-6-sources.jar",
          "url": "oitisdk-0.0.14-ofuscated-test-6-sources.jar",
          "size": 23829,
          "sha512": "02ec1c3e5dba9c085c217a6b2c6076d9b61b97c37b493126febb825cdf712c6803e57e53c83a8db2d981cfeed9370f1171becd89719a7055697a1ebd79394d63",
          "sha256": "65a5a131ce683ec2bb63fcd64f274151e0821e10a2aba7413f448378ff8c7dd0",
          "sha1": "2377fd168e7b6b1317f2f2a7d53bae448bf318b1",
          "md5": "98d3dafedd55b20a022db73acd954d9d"
        }
      ]
    }
  ]
}
