{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0-snapshot-2.aar",
          "url": "domain-1.2.0-snapshot-2.aar",
          "size": 156589,
          "sha512": "37bc2c78b95a078e827b8c129cde57e73dfc0dd78cff22416f977edf805455603ca69fff5fcdabf04a72161000a2fe160a57ee961156041560148b5a6ee2f76d",
          "sha256": "e415155fbfdfd7089b2ed5ff6ddc0e365f07d685277c313cff5306590618c03e",
          "sha1": "9924e415e0e961f9f9ee3c23239611bbe7d194fb",
          "md5": "a4433e8c7a4ee807b73384898c6977e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0-snapshot-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0-snapshot-2.aar",
          "url": "domain-1.2.0-snapshot-2.aar",
          "size": 156589,
          "sha512": "37bc2c78b95a078e827b8c129cde57e73dfc0dd78cff22416f977edf805455603ca69fff5fcdabf04a72161000a2fe160a57ee961156041560148b5a6ee2f76d",
          "sha256": "e415155fbfdfd7089b2ed5ff6ddc0e365f07d685277c313cff5306590618c03e",
          "sha1": "9924e415e0e961f9f9ee3c23239611bbe7d194fb",
          "md5": "a4433e8c7a4ee807b73384898c6977e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.0-snapshot-2-sources.jar",
          "url": "domain-1.2.0-snapshot-2-sources.jar",
          "size": 38998,
          "sha512": "3d251f9158082042923f1e79829dd02ae2e778c64db12a593c593d05feed3e910c99122782c0527d834fbd957cc4d702f0857b5bf71f849b7a0e6f0b18fc1746",
          "sha256": "8215be92a0f2078d1026d2bb508d5f9bd72e38ef0d41073681f308c496689833",
          "sha1": "760157fdaa7ae452c42de920bd292413ebadb9ba",
          "md5": "81759b207fc533416ff7950adb2cd171"
        }
      ]
    }
  ]
}
