{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "0.0.14-ofuscated-test-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-4.aar",
          "url": "utils-0.0.14-ofuscated-test-4.aar",
          "size": 65258,
          "sha512": "5741355b170e46095649fb54301781fc30a95a5d4ae5229ba5180ddf8882bca5fdb63164ce95b5069276bd1c6649ee31956f8a6a536fb8542b215cd555a5715c",
          "sha256": "cb85441f3d6cd0fe30798997a582ac736b7d3bdfa1d710f750cc06a02ae0d3b8",
          "sha1": "7d1e0a144bed1449eff67979dca3797e86bb4a32",
          "md5": "f4000996b76bd78e64b22e99fed2b808"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-4.aar",
          "url": "utils-0.0.14-ofuscated-test-4.aar",
          "size": 65258,
          "sha512": "5741355b170e46095649fb54301781fc30a95a5d4ae5229ba5180ddf8882bca5fdb63164ce95b5069276bd1c6649ee31956f8a6a536fb8542b215cd555a5715c",
          "sha256": "cb85441f3d6cd0fe30798997a582ac736b7d3bdfa1d710f750cc06a02ae0d3b8",
          "sha1": "7d1e0a144bed1449eff67979dca3797e86bb4a32",
          "md5": "f4000996b76bd78e64b22e99fed2b808"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-4-sources.jar",
          "url": "utils-0.0.14-ofuscated-test-4-sources.jar",
          "size": 36092,
          "sha512": "d60d9262d6158015caf268877ae5e27e4e97145299ebcaf9c57f54fc66319501523b3ac477e9e7ac5d6dfa0d2e4c7dc2b741ed9a511dd3e3a27e5b106d7bed3b",
          "sha256": "be30a960e15196cceb649cd5a68900d38bf6c00dddda7828dba837effc7ecf57",
          "sha1": "ae40adec58ebb0578ed88ce365595254f129dbae",
          "md5": "d1f98631b6073b34cca64574e509abd2"
        }
      ]
    }
  ]
}
