{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.8.aar",
          "url": "data-0.0.8.aar",
          "size": 168834,
          "sha512": "e358192d9758ee55b2d9da854751034e14f7d817db430afd07a67aa5158776bbf79e6582f9d0c0f57e05f25438cdbdc3860476fd81b0a5cbcd9df56e31e17ec8",
          "sha256": "42368f1663e96c3ffb5944c5e0de763e050bcf53776ae1cc2265958cef12d957",
          "sha1": "8747f1c29216aac8ae8af06ec6dc803dc65b13b6",
          "md5": "8838984ad6893cd2422fc0f02192324e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.8.aar",
          "url": "data-0.0.8.aar",
          "size": 168834,
          "sha512": "e358192d9758ee55b2d9da854751034e14f7d817db430afd07a67aa5158776bbf79e6582f9d0c0f57e05f25438cdbdc3860476fd81b0a5cbcd9df56e31e17ec8",
          "sha256": "42368f1663e96c3ffb5944c5e0de763e050bcf53776ae1cc2265958cef12d957",
          "sha1": "8747f1c29216aac8ae8af06ec6dc803dc65b13b6",
          "md5": "8838984ad6893cd2422fc0f02192324e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-0.0.8-sources.jar",
          "url": "data-0.0.8-sources.jar",
          "size": 14499,
          "sha512": "9b9fe84204dcd517c15f0748350b0db5af3bd1c9937aa07c85dbf5c3598cfd3a2526bd75e11a28d4df59da3a206b2c769e490103ee2fc4e9a58178613cb20e9d",
          "sha256": "9c680d5677fd0b4cf1e8aa8745ff3387114186a74b5212c7ded1566c4f8f20d9",
          "sha1": "cdb7fbd900addd17f395e45872fa6d6c579bf85c",
          "md5": "4f4aac6a8083c76a0c9d51c49822199d"
        }
      ]
    }
  ]
}
