{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "2.0.2-beta-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.2-beta-2.aar",
          "url": "certifacesdk-2.0.2-beta-2.aar",
          "size": 190920,
          "sha512": "3e3c4d3d0c5c3fc8e1cdeca694e12cad4cb37364e81292ade25f87439adb5620ca14b92fcb840adbcc5887d871169a17c7d4832804c383602f6e0d4e8e93fed2",
          "sha256": "62709c3e064603de09c82d638f988b6631d9a641ef3f98e78993867ab8b8c78a",
          "sha1": "50055f5773fe2324fca88158dcf67f6522bd4ac1",
          "md5": "0adfaa8e184b70e39fbb031f4aa5dbf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.2-beta-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.2-beta-2.aar",
          "url": "certifacesdk-2.0.2-beta-2.aar",
          "size": 190920,
          "sha512": "3e3c4d3d0c5c3fc8e1cdeca694e12cad4cb37364e81292ade25f87439adb5620ca14b92fcb840adbcc5887d871169a17c7d4832804c383602f6e0d4e8e93fed2",
          "sha256": "62709c3e064603de09c82d638f988b6631d9a641ef3f98e78993867ab8b8c78a",
          "sha1": "50055f5773fe2324fca88158dcf67f6522bd4ac1",
          "md5": "0adfaa8e184b70e39fbb031f4aa5dbf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-2.0.2-beta-2-sources.jar",
          "url": "certifacesdk-2.0.2-beta-2-sources.jar",
          "size": 68322,
          "sha512": "bf49bc1f42a7de3c3fd45840146ac6ae5c2bc9bbdd7993cbf6126f815baf880d07a9959dd225af25f8794262bfb80c98022e72339ba867672ea41b64cf4c0f98",
          "sha256": "e2af35c1cbe96c2520676673a989d395f1140927187457a0eac6894879b69e7a",
          "sha1": "8316d06c690870e6421e6ca5d04420df5214b257",
          "md5": "c251b324f5bc77956d695859c23339d2"
        }
      ]
    }
  ]
}
