{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.2.0.aar",
          "url": "data-1.2.0.aar",
          "size": 190170,
          "sha512": "01d3ef1e9147bb01772f611f24384672ed245bff24e60a27b46296896eccbffcb9dca2e2c215fd4eccc10abdd9ca0596b903e44ddbf1ce4d110dcc0183a72027",
          "sha256": "eb506242e525e7cac7b3547875c622f1c2682ff3b9578f78cf691b028ce8e0d8",
          "sha1": "fb71be51eb6d16f777f6da13b1c8e880da9b4e79",
          "md5": "346185149d5d2f864097e760c56d87ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.2.0.aar",
          "url": "data-1.2.0.aar",
          "size": 190170,
          "sha512": "01d3ef1e9147bb01772f611f24384672ed245bff24e60a27b46296896eccbffcb9dca2e2c215fd4eccc10abdd9ca0596b903e44ddbf1ce4d110dcc0183a72027",
          "sha256": "eb506242e525e7cac7b3547875c622f1c2682ff3b9578f78cf691b028ce8e0d8",
          "sha1": "fb71be51eb6d16f777f6da13b1c8e880da9b4e79",
          "md5": "346185149d5d2f864097e760c56d87ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.2.0-sources.jar",
          "url": "data-1.2.0-sources.jar",
          "size": 21749,
          "sha512": "4930156575f52d868492c5a680697ede588c233cea2090ffc8c7b29b03f1194f6a9fce57b791d25b7c4e5c96c568d9ca6291698e635a450924b2776448e11d4a",
          "sha256": "821764d8ad5f26c9b23ef3e916e91838fe8e1a4d2d76ac97f23967db1141c9e6",
          "sha1": "dffd007212a86e7843422be965720bda85b9c661",
          "md5": "874295dbbd5ff416512244fb44777a82"
        }
      ]
    }
  ]
}
