{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "2.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.0-beta.aar",
          "url": "data-2.0.0-beta.aar",
          "size": 237636,
          "sha512": "e39df58472cd4b11dd77566b8e434376943f321dddb25baa06635080c575c5b3416e64180a4e1a35bb8d90252e082a876c9164e53fd349e7e3cfdf29d41150a5",
          "sha256": "728a6404eab4c01165854a0a7f0343af5da1dfa9b5e6af9c394c9041fd9e812d",
          "sha1": "049645de08c480d8e7baef8d2faa3dfbe7685a8c",
          "md5": "e28d1bacbddffb2ca2bf6631ea0eaa88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.0-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.0-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.0-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.0-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.0-beta.aar",
          "url": "data-2.0.0-beta.aar",
          "size": 237636,
          "sha512": "e39df58472cd4b11dd77566b8e434376943f321dddb25baa06635080c575c5b3416e64180a4e1a35bb8d90252e082a876c9164e53fd349e7e3cfdf29d41150a5",
          "sha256": "728a6404eab4c01165854a0a7f0343af5da1dfa9b5e6af9c394c9041fd9e812d",
          "sha1": "049645de08c480d8e7baef8d2faa3dfbe7685a8c",
          "md5": "e28d1bacbddffb2ca2bf6631ea0eaa88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-2.0.0-beta-sources.jar",
          "url": "data-2.0.0-beta-sources.jar",
          "size": 34777,
          "sha512": "8f533d029eab4ffded134e3baf8f4477bdbccb322ff6b09aebb9dfde60c1a4f237a78f149d229e4b5e0f5c54866e6d0b3e66975580ce120b172378343201999f",
          "sha256": "6c7bb90c6f091e552ccad4864b52e7969a17898774ed0226d2bfc84d7cdf3bdb",
          "sha1": "cd951b2d8778c547eb6cd1f594dc06a86fac3525",
          "md5": "3f4e2042fc63a7d145769581688cfb10"
        }
      ]
    }
  ]
}
