{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "0.0.14-ofuscated-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test.aar",
          "url": "utils-0.0.14-ofuscated-test.aar",
          "size": 64705,
          "sha512": "2e0fee50ce0ca5d8ea63d30bb0d81e6314decf0ca9389ce1a7d67c07584327a9072deb3b00ea615c47b5a167805a0295a790e562d6b7a40ce026e85f2357ade2",
          "sha256": "95ed61242e3fbf93f38fafe6a058d90e2a4a3b76fdcd0ecb96aece3ad625f65a",
          "sha1": "4125f4b71b1116f7caffd2af46bd56b076926ace",
          "md5": "3aa9971729bb9499ac9b20856f89b161"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test.aar",
          "url": "utils-0.0.14-ofuscated-test.aar",
          "size": 64705,
          "sha512": "2e0fee50ce0ca5d8ea63d30bb0d81e6314decf0ca9389ce1a7d67c07584327a9072deb3b00ea615c47b5a167805a0295a790e562d6b7a40ce026e85f2357ade2",
          "sha256": "95ed61242e3fbf93f38fafe6a058d90e2a4a3b76fdcd0ecb96aece3ad625f65a",
          "sha1": "4125f4b71b1116f7caffd2af46bd56b076926ace",
          "md5": "3aa9971729bb9499ac9b20856f89b161"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.14-ofuscated-test-sources.jar",
          "url": "utils-0.0.14-ofuscated-test-sources.jar",
          "size": 35808,
          "sha512": "1d0565e0cf8174a2c09b395a0ff20144c97b3ca36dac6471fabdb10ebd9cbf5bfd637c7d1bef3af5cb00fb570a88464c7ce048d1ec1ff59eb89551a3ce2a9fe5",
          "sha256": "e622825f46fc9c7fa5c68a865ba72df9ba268126acab37822efefb3a214b7781",
          "sha1": "0fca6ba5614a23d3e7fe46fabc7629b9a9476cf5",
          "md5": "00b4d2bb9f0a49be36801d8190d0fb96"
        }
      ]
    }
  ]
}
