{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certiface-network",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certiface-network-1.2.0.aar",
          "url": "certiface-network-1.2.0.aar",
          "size": 27614,
          "sha512": "8065b85147057284a91f65ce500c7adb6f6f2546b05fdceff6da1783eb9590a23421a06718b9816d55cce840f98dcc7c74ae2a17dc469d927a0d9722efee36d0",
          "sha256": "df5f8ab5d21857fc940a1718524f5228f1d6dd54a744f855036f52fc4e59eabc",
          "sha1": "ac6c3b28341d691894f0ced5316a4a149012ed29",
          "md5": "bcc99b9334d7455b25c01d8f5da5614c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certiface-network-1.2.0.aar",
          "url": "certiface-network-1.2.0.aar",
          "size": 27614,
          "sha512": "8065b85147057284a91f65ce500c7adb6f6f2546b05fdceff6da1783eb9590a23421a06718b9816d55cce840f98dcc7c74ae2a17dc469d927a0d9722efee36d0",
          "sha256": "df5f8ab5d21857fc940a1718524f5228f1d6dd54a744f855036f52fc4e59eabc",
          "sha1": "ac6c3b28341d691894f0ced5316a4a149012ed29",
          "md5": "bcc99b9334d7455b25c01d8f5da5614c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certiface-network-1.2.0-sources.jar",
          "url": "certiface-network-1.2.0-sources.jar",
          "size": 14652,
          "sha512": "35515634e80d12c570bb540efba4bcc245c467328784ae2479e76d390dde65a9b62c94759cf5af64e9b616b18c246d50a61ae8f2296385f45beb640c6460494a",
          "sha256": "2d90266d4f1fcddee8d874601edcfa466f9cd62719da65eb12850d921eb526fe",
          "sha1": "1c3bf39fe4e2df0e114ce6084ee86cde95ff010c",
          "md5": "557bd2fedc3982aba42d3383f4a2f790"
        }
      ]
    }
  ]
}
