{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.2.aar",
          "url": "certifacesdk-2.0.2.aar",
          "size": 190864,
          "sha512": "b441f153ae5f37efdd907511718316c20950e048f1f66296a5fc6f577f1cdd30dd4ccd73b78a2b0816eaa1fba68012efb9ade749bc9b67c0b261bf5952fdc056",
          "sha256": "e10e3ecba563652406d017ab3f5dd2e92fd8a08b7fbfc614719a776dc96a1e4d",
          "sha1": "8d8c45d9757c46fbc5c10da5b76bedd39e580888",
          "md5": "718da88618e4df10f06ce1295b90b437"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.2.aar",
          "url": "certifacesdk-2.0.2.aar",
          "size": 190864,
          "sha512": "b441f153ae5f37efdd907511718316c20950e048f1f66296a5fc6f577f1cdd30dd4ccd73b78a2b0816eaa1fba68012efb9ade749bc9b67c0b261bf5952fdc056",
          "sha256": "e10e3ecba563652406d017ab3f5dd2e92fd8a08b7fbfc614719a776dc96a1e4d",
          "sha1": "8d8c45d9757c46fbc5c10da5b76bedd39e580888",
          "md5": "718da88618e4df10f06ce1295b90b437"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-2.0.2-sources.jar",
          "url": "certifacesdk-2.0.2-sources.jar",
          "size": 68219,
          "sha512": "357421e4113088dc00d95474e4228bbbce9a394f8ae99e0ab1fe6125a38d8bdeeeb95f27815b3c8187b2b2228a1fd0c3e34cc0f5cc777c8061e39002a99bd685",
          "sha256": "391b77262156b11d740fc2323753d93a99e8a65613ce48fbef306cd1784250bb",
          "sha1": "0f86bc0692a35c690ac29f36139ecc60670a7053",
          "md5": "cbc8e286d760ffa79fdca80187e75ec1"
        }
      ]
    }
  ]
}
