{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "2.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.4-beta.aar",
          "url": "certifacesdk-2.0.4-beta.aar",
          "size": 210685,
          "sha512": "d25ef3e4996b9a2134c60035c6e365e7e2530a6c935dc72dc047a0ce875ab02e13bce65118d6f481dd113f266ce97aa9d003591462316e33c7e8610dc4fb0986",
          "sha256": "7389f2c1536eed509367be0c8f393b2fe2941477d0ce6f6e3249879b654218c2",
          "sha1": "43f917cda4e1d039551f017b117e0954f60bcb16",
          "md5": "6aab1fd1550026aab13fbfe7320d2916"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.4-beta.aar",
          "url": "certifacesdk-2.0.4-beta.aar",
          "size": 210685,
          "sha512": "d25ef3e4996b9a2134c60035c6e365e7e2530a6c935dc72dc047a0ce875ab02e13bce65118d6f481dd113f266ce97aa9d003591462316e33c7e8610dc4fb0986",
          "sha256": "7389f2c1536eed509367be0c8f393b2fe2941477d0ce6f6e3249879b654218c2",
          "sha1": "43f917cda4e1d039551f017b117e0954f60bcb16",
          "md5": "6aab1fd1550026aab13fbfe7320d2916"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-2.0.4-beta-sources.jar",
          "url": "certifacesdk-2.0.4-beta-sources.jar",
          "size": 69471,
          "sha512": "123b583588fda762fb065a2da866e229677b7ff6bb655a530c369339ff799b1188fdc02c3a3641763ae9a11fa37b87ab976449363c012fc082bfbcee0d50c182",
          "sha256": "2c516772c2ecf0d10ba170148293ba736e3b23b9ab4979587e5477cefbf6f87d",
          "sha1": "43c8d49563795656af4f84dd6fbe8d8c0b6933c2",
          "md5": "0fffad466772e64b0626b3032f2b39e1"
        }
      ]
    }
  ]
}
