{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "remote",
    "version": "1.2.1-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.2.1-snapshot-1.aar",
          "url": "remote-1.2.1-snapshot-1.aar",
          "size": 12900,
          "sha512": "5a6705747a9782d77be5ed17a647cae10de072c866e78605adcf836436e83aab9fba5e56b5a341495924b8124313cb64b4a9269b205a24e3acef1ad44755f2ec",
          "sha256": "8aab260140c3c05fd5e81b0540dbf5053307ff2dacdc9e13f3235591129ef8dd",
          "sha1": "bf13e9a5ebd21b650b0a4513a7e20157d3919250",
          "md5": "cd4c8002e6a413de924eca2dfca7d5d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.2.1-snapshot-1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "certiface-network",
          "version": {
            "requires": "1.2.1-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.2.1-snapshot-1.aar",
          "url": "remote-1.2.1-snapshot-1.aar",
          "size": 12900,
          "sha512": "5a6705747a9782d77be5ed17a647cae10de072c866e78605adcf836436e83aab9fba5e56b5a341495924b8124313cb64b4a9269b205a24e3acef1ad44755f2ec",
          "sha256": "8aab260140c3c05fd5e81b0540dbf5053307ff2dacdc9e13f3235591129ef8dd",
          "sha1": "bf13e9a5ebd21b650b0a4513a7e20157d3919250",
          "md5": "cd4c8002e6a413de924eca2dfca7d5d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-1.2.1-snapshot-1-sources.jar",
          "url": "remote-1.2.1-snapshot-1-sources.jar",
          "size": 7105,
          "sha512": "dc504ed00e5de4968d0f9f5b4457fd9c9c155be4a02c44c89f434eb63cab6b92463f257ff62be052bdc68399cd994d304a0fd0f118d94d025eb15618e3e258ef",
          "sha256": "858e2eb018ee5a96d44dfdd2d632198e90c124d09297a92e33459e2b87b958db",
          "sha1": "88553671120b88e44d7b25539acccb7a76d629a7",
          "md5": "51abcc36127c106fe35f3e5c82481c1c"
        }
      ]
    }
  ]
}
