{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.3.0.aar",
          "url": "logging-1.3.0.aar",
          "size": 57751,
          "sha512": "daedafb919c911a27f70dbc7aff3396a2dcd46a0e3fdf676608506aafc9b19ce2620fa9ac92de3ef9501c27936d94ffa73b873a37a1fcd823d2515a053c5aa2e",
          "sha256": "97e0b0bcc4d36e36b8c50580679979c2f0dfac225b6376ab0fc95cede5819fed",
          "sha1": "7c9e23849f676c7e9c3d337bffb408104c369f5b",
          "md5": "190364db3495e183c2b6db7b8a1c9156"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.3.0.aar",
          "url": "logging-1.3.0.aar",
          "size": 57751,
          "sha512": "daedafb919c911a27f70dbc7aff3396a2dcd46a0e3fdf676608506aafc9b19ce2620fa9ac92de3ef9501c27936d94ffa73b873a37a1fcd823d2515a053c5aa2e",
          "sha256": "97e0b0bcc4d36e36b8c50580679979c2f0dfac225b6376ab0fc95cede5819fed",
          "sha1": "7c9e23849f676c7e9c3d337bffb408104c369f5b",
          "md5": "190364db3495e183c2b6db7b8a1c9156"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.3.0-sources.jar",
          "url": "logging-1.3.0-sources.jar",
          "size": 24691,
          "sha512": "05096aaab259da2a6a681f3cf6d11d42387eab1786ee2b19cfb709d859403dc2983809eb17eed815fa344888e19e53dd5162bd70f4605ea9b73192102ff939ec",
          "sha256": "19b514a29c79f3b072ded71aaeed9dba3e0dda8914a096a92d279f8206710f10",
          "sha1": "81469677974aa739bb0ad6e5cc36d23e115803db",
          "md5": "85265cde0754eac72c18325ffbc888df"
        }
      ]
    }
  ]
}
