{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "iproovsdk",
    "version": "0.0.14-ofuscated-test-7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "iproovsdk-0.0.14-ofuscated-test-7.aar",
          "url": "iproovsdk-0.0.14-ofuscated-test-7.aar",
          "size": 87817,
          "sha512": "fc441fef443a03b2a5f4f4ccce42f1364cff74b3c732da3eb15b34789061fb4591b28da9d1672568503f746a2e2359c0c6e2766fb2fa3763e634cec641d18203",
          "sha256": "829dbbe1b284bc610d52be349b7983f1818043883b52c9ae0d97a59c6c1ca9ca",
          "sha1": "88d79dcbe31b3d79a8e99b918c2ee7815ea7b3b1",
          "md5": "b396ee185db8ab04bad6521b15eaa7fb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.36.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.14-ofuscated-test-7"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.14-ofuscated-test-7"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.14-ofuscated-test-7"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.14-ofuscated-test-7"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.14-ofuscated-test-7"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "iproovsdk-0.0.14-ofuscated-test-7.aar",
          "url": "iproovsdk-0.0.14-ofuscated-test-7.aar",
          "size": 87817,
          "sha512": "fc441fef443a03b2a5f4f4ccce42f1364cff74b3c732da3eb15b34789061fb4591b28da9d1672568503f746a2e2359c0c6e2766fb2fa3763e634cec641d18203",
          "sha256": "829dbbe1b284bc610d52be349b7983f1818043883b52c9ae0d97a59c6c1ca9ca",
          "sha1": "88d79dcbe31b3d79a8e99b918c2ee7815ea7b3b1",
          "md5": "b396ee185db8ab04bad6521b15eaa7fb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "iproovsdk-0.0.14-ofuscated-test-7-sources.jar",
          "url": "iproovsdk-0.0.14-ofuscated-test-7-sources.jar",
          "size": 51572,
          "sha512": "f5a53eaef177d09a0ae4dabd3fb71e20ec9527cb2f024ac2aa48c12c8477a196622c106d6e989aab64d67a996045509cd82da35b1af8ee6cfe7ae508e4d21d21",
          "sha256": "6e615b3e48d85af4a6e6060923bfd29f37d98233f3a3e9c8e8f3ac70e4a1b62c",
          "sha1": "a91c27ba703ac7eaffe44dd5ff476789d21e8d5e",
          "md5": "ab39e7e24e2ff8a944485abb2432bc44"
        }
      ]
    }
  ]
}
