{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.manager",
    "module": "oitiSDK",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "OitiSDK",
          "module": "OitiDI",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiCore",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiDomain",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiRemote",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiNetwork",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiDesignSystem",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiUtils",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiLogging",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiData",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "IProovSDK",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitiSDK-1.0.0.aar",
          "url": "oitiSDK-1.0.0.aar",
          "size": 48404,
          "sha512": "f94a0a3577c1619edcb724804b5464bc54b11865d7c43fb5779698605d532c9210e69c590bc81b4dc46230ee1870738cb64d44fdf01090d447ea34005b2efadf",
          "sha256": "ed7c422f2a8347f2f8d9712a524d60123f6cc0fddf62f6e509703d443157705f",
          "sha1": "7dd852c9d8619b15a387886445bb81d17d1069ae",
          "md5": "21cf9f0bf0a7947d8bf310a855604b5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiDI",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiCore",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiDomain",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiRemote",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiNetwork",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiDesignSystem",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiUtils",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiLogging",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "OitiData",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "OitiSDK",
          "module": "IProovSDK",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitiSDK-1.0.0.aar",
          "url": "oitiSDK-1.0.0.aar",
          "size": 48404,
          "sha512": "f94a0a3577c1619edcb724804b5464bc54b11865d7c43fb5779698605d532c9210e69c590bc81b4dc46230ee1870738cb64d44fdf01090d447ea34005b2efadf",
          "sha256": "ed7c422f2a8347f2f8d9712a524d60123f6cc0fddf62f6e509703d443157705f",
          "sha1": "7dd852c9d8619b15a387886445bb81d17d1069ae",
          "md5": "21cf9f0bf0a7947d8bf310a855604b5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oitiSDK-1.0.0-sources.jar",
          "url": "oitiSDK-1.0.0-sources.jar",
          "size": 15570,
          "sha512": "3c402a23b5fe7a8c0f920a9d6b8cd61e2764007deefbcd6c5e90554dd61d344ff135794e8a4243150e38b501e1e78c0c0e7c971896f6b3f8d7133396842514d3",
          "sha256": "3cdb8786522f981b010f67f3a3d5a925c20722d18d521d2384863654790decbf",
          "sha1": "df5d9502554376693268f306ebedcbee40438529",
          "md5": "e81f0dddaac6f0ddc420167c8d18bb80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oitiSDK-1.0.0-javadoc.jar",
          "url": "oitiSDK-1.0.0-javadoc.jar",
          "size": 345570,
          "sha512": "19955b9ad1537f1742455cf0ffc7692483c5a585f6c6173fd0467acd6f18a978af207624a29075b41485eb8b15b35708bdf06383f6fdda01f7e793f782628153",
          "sha256": "c4d16510eebf1e0e99d8079cf9cd2eca467872b10426f40242eab2da86bf9352",
          "sha1": "ac698ba70c56a0f758cdb3ae5656eeed884c4edb",
          "md5": "12a630aea414317b2ac2665e5fa51557"
        }
      ]
    }
  ]
}
