{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-2.0.2.aar",
          "url": "logging-2.0.2.aar",
          "size": 66516,
          "sha512": "f69a0cdcf77c9f3edda7487c19ea14dfb9bc28217aaf617a007933d2d6769250dd8c3f246c5ddb67ad1939a535b8cd906ff2511b71847f6c3ddf4ae3c860aa0e",
          "sha256": "fa93014d87852d6049aacc28664d42cd047e9e5a4d92337cfeeaa260423db72c",
          "sha1": "62d2b33ce2adffeb6f6526ddd53c5acea9fb47e5",
          "md5": "9a28e325bde71f6995c18791b79afaac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-2.0.2.aar",
          "url": "logging-2.0.2.aar",
          "size": 66516,
          "sha512": "f69a0cdcf77c9f3edda7487c19ea14dfb9bc28217aaf617a007933d2d6769250dd8c3f246c5ddb67ad1939a535b8cd906ff2511b71847f6c3ddf4ae3c860aa0e",
          "sha256": "fa93014d87852d6049aacc28664d42cd047e9e5a4d92337cfeeaa260423db72c",
          "sha1": "62d2b33ce2adffeb6f6526ddd53c5acea9fb47e5",
          "md5": "9a28e325bde71f6995c18791b79afaac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-2.0.2-sources.jar",
          "url": "logging-2.0.2-sources.jar",
          "size": 27620,
          "sha512": "2f34ac6bcf738411e2291a6a55a017d0617c94413f040410cca386280c6f3013008aad943359ad8e7055875e6e12465e935eaefe7bd023154203830f8326f4e9",
          "sha256": "d69dae36b8ff7f9ecceadf391fb4687b7faab7f9d408ee97d5ad06e3efe1b214",
          "sha1": "037f7fb106e8f88fedb9a45ad7ec06657026c23a",
          "md5": "1b465f66ad0398840316487ddc69ddc7"
        }
      ]
    }
  ]
}
