{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-2.0.2.aar",
          "url": "logging-2.0.2.aar",
          "size": 63668,
          "sha512": "f5adca7299bf4aa60d55091091b88d46d20f89b90f2303742195992b4114762658722826c1e5f019580ef9f156dbd8afa02fdbb16568e19a448a4a2018d9150d",
          "sha256": "723e0ee2c3674afbe010a0a722a0e0c973b720a54b2c722b48e6efcb68bb567e",
          "sha1": "015d2912d1141a3a0578a566d0e622108ba2bce2",
          "md5": "7904f620e804bc8fb94b2cb7ca6f8c3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-2.0.2.aar",
          "url": "logging-2.0.2.aar",
          "size": 63668,
          "sha512": "f5adca7299bf4aa60d55091091b88d46d20f89b90f2303742195992b4114762658722826c1e5f019580ef9f156dbd8afa02fdbb16568e19a448a4a2018d9150d",
          "sha256": "723e0ee2c3674afbe010a0a722a0e0c973b720a54b2c722b48e6efcb68bb567e",
          "sha1": "015d2912d1141a3a0578a566d0e622108ba2bce2",
          "md5": "7904f620e804bc8fb94b2cb7ca6f8c3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-2.0.2-sources.jar",
          "url": "logging-2.0.2-sources.jar",
          "size": 27510,
          "sha512": "ec82745c1f00f75fd87376d2860b005c7ba058ce046b04d80f1cc994bb7a99de158c79f1e75fe5e42ea91b9b27105e80bc8ca4f38a378333ccd28619634c4875",
          "sha256": "2c16345aa7486b5448f2c6b071cb4c22971bc1d0f34be08ebf9e1f6333543733",
          "sha1": "e6c9b3e0f2a8bc6008576c626abdb9094c01f3fb",
          "md5": "847af7c58b1d000caac9f0f8da3cfa32"
        }
      ]
    }
  ]
}
