{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "2.0.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-2.0.3-beta.aar",
          "url": "logging-2.0.3-beta.aar",
          "size": 66844,
          "sha512": "35ac34528c824eb8945bee4cf6978c33d883f4470b808dcc2bad451c8eb52e071185f145f8862813cd4785d0be735ed75dc969bc3ebc55ab5603f665ce5d559b",
          "sha256": "46f3d8a886d2266e45ddbd6236d39d5b0eac211f5f507be11b16c76cb2279c51",
          "sha1": "1640d95e7e73234e65808a3b8e04b0adda17578b",
          "md5": "d6419507cdee026e9315e6cf3a5603df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.3-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-2.0.3-beta.aar",
          "url": "logging-2.0.3-beta.aar",
          "size": 66844,
          "sha512": "35ac34528c824eb8945bee4cf6978c33d883f4470b808dcc2bad451c8eb52e071185f145f8862813cd4785d0be735ed75dc969bc3ebc55ab5603f665ce5d559b",
          "sha256": "46f3d8a886d2266e45ddbd6236d39d5b0eac211f5f507be11b16c76cb2279c51",
          "sha1": "1640d95e7e73234e65808a3b8e04b0adda17578b",
          "md5": "d6419507cdee026e9315e6cf3a5603df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-2.0.3-beta-sources.jar",
          "url": "logging-2.0.3-beta-sources.jar",
          "size": 27579,
          "sha512": "98821bebcc671e10f9a23a123ca8314198a3514a892bbfc321470a87e8413c137ad33b962935184d187522234bca3b03ed5dcef68922dacd5af9bc2d95be77cf",
          "sha256": "6268019edc706b891fbf46b6a6daa05a56603d0616b758b41fe4558333670b79",
          "sha1": "794d1b4601add1a3c9f7ec91c06f7ba4363d1c83",
          "md5": "f7787dbfa3555de13c42ff383002b54d"
        }
      ]
    }
  ]
}
