{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.3.aar",
          "url": "data-2.0.3.aar",
          "size": 237602,
          "sha512": "35481e16a87bc28ddcb83f60339262427555738d1e861865157ea765fd350d5532fd1319f29d802f1a495cf7f392edb82ca07979ae5dfc48cf435a3288a30a07",
          "sha256": "f6ec06e23d4b349468b3a55b9f4f0c29c360567b6f80dd4ccc061bb1514076af",
          "sha1": "168c287da96e3fae3463ffc61f1309a0e12a6f69",
          "md5": "ef3855006ac9c50759069e0e5e900cb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-2.0.3.aar",
          "url": "data-2.0.3.aar",
          "size": 237602,
          "sha512": "35481e16a87bc28ddcb83f60339262427555738d1e861865157ea765fd350d5532fd1319f29d802f1a495cf7f392edb82ca07979ae5dfc48cf435a3288a30a07",
          "sha256": "f6ec06e23d4b349468b3a55b9f4f0c29c360567b6f80dd4ccc061bb1514076af",
          "sha1": "168c287da96e3fae3463ffc61f1309a0e12a6f69",
          "md5": "ef3855006ac9c50759069e0e5e900cb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-2.0.3-sources.jar",
          "url": "data-2.0.3-sources.jar",
          "size": 34853,
          "sha512": "01f320d68980e644f10690df7a9b4f09ffeea191ebb90d84b410b2c4b31f811157f02e354ca6f234219ea0f78313152dea6a5a75e1cd1a63617c356f7af9e111",
          "sha256": "c992d42b62a6a827a37d0ab6603aa1f283a438236245309b0bd45b4b84960704",
          "sha1": "1c0c71c304d400201ec150056f7a6bf7f5010298",
          "md5": "867429c3a368a15b5d49881e49ab58b5"
        }
      ]
    }
  ]
}
