{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "2.0.4-beta-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.4-beta-2.aar",
          "url": "certifacesdk-2.0.4-beta-2.aar",
          "size": 212261,
          "sha512": "169bdec563e1fa1a17f1ba51e399702b51f4ce49046eda1ba138acbace200254ecb79472b8e244f642705c09663c76bd762f13a701bd00bb400cf55802da3ea5",
          "sha256": "f411729b59f41e4e366c1de4e60407a9bb7d50d1e1ba8063337fe8fa992b3ac0",
          "sha1": "e81c6bb722563e2c4648587ed76f1c6212334b3c",
          "md5": "669db2fb3ac9d902562957035215d8dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "fortfacesdk",
          "version": {
            "requires": "2.0.4-beta-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-2.0.4-beta-2.aar",
          "url": "certifacesdk-2.0.4-beta-2.aar",
          "size": 212261,
          "sha512": "169bdec563e1fa1a17f1ba51e399702b51f4ce49046eda1ba138acbace200254ecb79472b8e244f642705c09663c76bd762f13a701bd00bb400cf55802da3ea5",
          "sha256": "f411729b59f41e4e366c1de4e60407a9bb7d50d1e1ba8063337fe8fa992b3ac0",
          "sha1": "e81c6bb722563e2c4648587ed76f1c6212334b3c",
          "md5": "669db2fb3ac9d902562957035215d8dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-2.0.4-beta-2-sources.jar",
          "url": "certifacesdk-2.0.4-beta-2-sources.jar",
          "size": 70576,
          "sha512": "843f79af62fdb9032c39f269b816d8ae843be4a18584dc6db0f37e13f87c6ccd97f3c20c7c752d646dd5d0286424c1cf0efaaa7511ad89b6fe649e6acb02ccf9",
          "sha256": "910a1ffb25845161063261e60e07bf8ae85cb5d04e8d0f8b85d7e705b13390e4",
          "sha1": "b37da2eab99f82f96e7b6b3c4e7e14080f4726ec",
          "md5": "cb564d91361cd2860a922556f9ffdacc"
        }
      ]
    }
  ]
}
