{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0.aar",
          "url": "domain-1.2.0.aar",
          "size": 162704,
          "sha512": "9a70ab88c46bb1905e4e8f6a01da3a60a3d9468c23f7b18581ab7f16d5b9a637067ed01fb9883f5e0ec583ad62fd20d24a2e2b6c9ab5ce0f9eee3fcbed80b7fb",
          "sha256": "12ffb89d5bf0b2b975fa306e0f7dd6544e3934e6d6bae0ce8917131ff7e2ddf1",
          "sha1": "9ca88811581af407cf3cf05bf15790524b75bcc9",
          "md5": "2fa165d0c7b0da8c7f8328621c66b835"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0.aar",
          "url": "domain-1.2.0.aar",
          "size": 162704,
          "sha512": "9a70ab88c46bb1905e4e8f6a01da3a60a3d9468c23f7b18581ab7f16d5b9a637067ed01fb9883f5e0ec583ad62fd20d24a2e2b6c9ab5ce0f9eee3fcbed80b7fb",
          "sha256": "12ffb89d5bf0b2b975fa306e0f7dd6544e3934e6d6bae0ce8917131ff7e2ddf1",
          "sha1": "9ca88811581af407cf3cf05bf15790524b75bcc9",
          "md5": "2fa165d0c7b0da8c7f8328621c66b835"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.0-sources.jar",
          "url": "domain-1.2.0-sources.jar",
          "size": 40104,
          "sha512": "a7da4fbbec8a41cb7cb47757899abbd02b842832141499ef35000727227b745ca549124f8a80a4f00634bff0955c77695144172f837023676aacdc04b8a8004c",
          "sha256": "f6cde8e18928225bfb8e934d68648f238082415c00b9bfb0e5a01a790f542e7e",
          "sha1": "a933b7913bfcc6963b5fd8d49da284aaf3f97e45",
          "md5": "7765f3611fe2edc80d6c66892abe815a"
        }
      ]
    }
  ]
}
