{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0.aar",
          "url": "domain-1.2.0.aar",
          "size": 164150,
          "sha512": "78b2ca2491b36e4f571bcf83fdb35d562bcac28c688aa766b3d06f02e8b30259354cdea18f33a475dddea58e5956c275c51d2aeed7126111ffc714c6ee2152ae",
          "sha256": "bbedc7778b77dc2433cd327f15ebb72b2672e293d22e059f8221725f611c1192",
          "sha1": "1efbdb4ba981944152ed68bedd687d82c0715be6",
          "md5": "7716a2dcdbd1b7bd6111c25982c47786"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0.aar",
          "url": "domain-1.2.0.aar",
          "size": 164150,
          "sha512": "78b2ca2491b36e4f571bcf83fdb35d562bcac28c688aa766b3d06f02e8b30259354cdea18f33a475dddea58e5956c275c51d2aeed7126111ffc714c6ee2152ae",
          "sha256": "bbedc7778b77dc2433cd327f15ebb72b2672e293d22e059f8221725f611c1192",
          "sha1": "1efbdb4ba981944152ed68bedd687d82c0715be6",
          "md5": "7716a2dcdbd1b7bd6111c25982c47786"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.0-sources.jar",
          "url": "domain-1.2.0-sources.jar",
          "size": 40293,
          "sha512": "230291063f7cf3a0550418b213229ca02846383f582f2a38db6383e651b4d58fea898074b8dc3eda5c1910c89306e718164ffa0359d98284f0c96af3ce543428",
          "sha256": "5ccf022a30bc66672da7f41add2ff4a4ff64e32229dc65cbd4dce4a291a8e917",
          "sha1": "93cb2e11df95434b4adecb6e4f334e190df777a3",
          "md5": "e5954e7e42d7d62a5d9f753e06cb9d2b"
        }
      ]
    }
  ]
}
