{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0.aar",
          "url": "domain-1.2.0.aar",
          "size": 156436,
          "sha512": "60e166f0d9a38d3193580d64cef0d1733b618c40208866d5c3e58538dbbef9c1309e09ff4505050152f795f983d6b7175bc0d5f8551f3cb778f7cc7abea2d070",
          "sha256": "23a9f8849ac25847ab576c43be9f05493530622ca8bd24ec880a454282f5b177",
          "sha1": "38d69a6bddfe8a3b8b8fc587cea188cdc736c6ec",
          "md5": "b7ec1e27a1a782aa5e81fabde9c46f41"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.0.aar",
          "url": "domain-1.2.0.aar",
          "size": 156436,
          "sha512": "60e166f0d9a38d3193580d64cef0d1733b618c40208866d5c3e58538dbbef9c1309e09ff4505050152f795f983d6b7175bc0d5f8551f3cb778f7cc7abea2d070",
          "sha256": "23a9f8849ac25847ab576c43be9f05493530622ca8bd24ec880a454282f5b177",
          "sha1": "38d69a6bddfe8a3b8b8fc587cea188cdc736c6ec",
          "md5": "b7ec1e27a1a782aa5e81fabde9c46f41"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.0-sources.jar",
          "url": "domain-1.2.0-sources.jar",
          "size": 38376,
          "sha512": "63c847efe60abd8e6c49c3a35f80832ff75f0a949b255280bf698d43a2a82a14378789a0e2ea95fd870c21061b8a7b360c18e40a3b972e6292fb9c50c23807f4",
          "sha256": "99557721578d2ed4b5525b3d6bd3004fd1df3ef13b8bccea209efe8e334bbc4d",
          "sha1": "d4442f272fba14c113a5778e028ea7d7fab6e669",
          "md5": "266f7ddff52224c7c928632cc7fe6004"
        }
      ]
    }
  ]
}
