{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.3.1-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.3.1-snapshot-3.aar",
          "url": "domain-1.3.1-snapshot-3.aar",
          "size": 216217,
          "sha512": "d3df58f084300f0aa3e8be6f9bce6bbd342bf2930162d433077d095d977438e53b3c9aa4cbc7b71745bf3d938ae8915beefecc3c0dd9dbca3957aecae021a1ae",
          "sha256": "e9e9dab7f5b8f70030e231891a03e7aee4b7b5dd4d88eb9bee861053c18a7855",
          "sha1": "b840cc03528993047290e4af1e9b99c01681ce44",
          "md5": "5944a993eee3986bdf5554eb2dad8840"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.3.1-snapshot-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.3.1-snapshot-3.aar",
          "url": "domain-1.3.1-snapshot-3.aar",
          "size": 216217,
          "sha512": "d3df58f084300f0aa3e8be6f9bce6bbd342bf2930162d433077d095d977438e53b3c9aa4cbc7b71745bf3d938ae8915beefecc3c0dd9dbca3957aecae021a1ae",
          "sha256": "e9e9dab7f5b8f70030e231891a03e7aee4b7b5dd4d88eb9bee861053c18a7855",
          "sha1": "b840cc03528993047290e4af1e9b99c01681ce44",
          "md5": "5944a993eee3986bdf5554eb2dad8840"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.3.1-snapshot-3-sources.jar",
          "url": "domain-1.3.1-snapshot-3-sources.jar",
          "size": 55255,
          "sha512": "ed28cc00836a5f0c8e579e8ed00d98231019446afde33e8de7758306b89755584386918f3ea74bfdad6d0b2347678e54ac29194e0e2b80b5ab621610dc08afaf",
          "sha256": "4374b55a77512520eeff8ee6d095030576f69c8a70805df3bb57c264e904f39e",
          "sha1": "de7a2565c5458e3adf19b5de097eec1742ed46a0",
          "md5": "71bf0bc2f57a4e8d0941587739608f76"
        }
      ]
    }
  ]
}
