{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "2.0.0-beta-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-2.0.0-beta-3.aar",
          "url": "domain-2.0.0-beta-3.aar",
          "size": 216222,
          "sha512": "0bf2f515cd922be16feb84bbc77c128cfb41de95ccb939bd5ea100557484952ebaa8dad79fd8b2d1eb936e1ed01712f436463fe0ee6ddc9896878dc57ac9f412",
          "sha256": "2c49809bd59c2e094558cc646ad1215a194033ad0b128bfa86ca78492c55e894",
          "sha1": "4e899ce9e5cadffce1dfb009f11a7333aadd7cf9",
          "md5": "f6f1e4f7155c96391c6557a9aa3c0d61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.0-beta-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-2.0.0-beta-3.aar",
          "url": "domain-2.0.0-beta-3.aar",
          "size": 216222,
          "sha512": "0bf2f515cd922be16feb84bbc77c128cfb41de95ccb939bd5ea100557484952ebaa8dad79fd8b2d1eb936e1ed01712f436463fe0ee6ddc9896878dc57ac9f412",
          "sha256": "2c49809bd59c2e094558cc646ad1215a194033ad0b128bfa86ca78492c55e894",
          "sha1": "4e899ce9e5cadffce1dfb009f11a7333aadd7cf9",
          "md5": "f6f1e4f7155c96391c6557a9aa3c0d61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-2.0.0-beta-3-sources.jar",
          "url": "domain-2.0.0-beta-3-sources.jar",
          "size": 55265,
          "sha512": "1aa9c90bae77c6a88c05fc198b74fcce282d95d172c03d62a5e6ed63a6d2f3857f813289049a5596ad074f256d3ee4120e7fd6d4997600fa6253c57a7df0d410",
          "sha256": "63b3ce0d4a9cc335d1e18983837ae54851ad0a6f65257b9988891602ed128e1b",
          "sha1": "39a7d94eb220a2e14673605e13e266921d2f3570",
          "md5": "45d908d43cd03be5c6971d6a52e87cb2"
        }
      ]
    }
  ]
}
