{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "fortfacesdk",
    "version": "2.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "fortfacesdk-2.0.2-beta.aar",
          "url": "fortfacesdk-2.0.2-beta.aar",
          "size": 240374,
          "sha512": "bccc2c04c5c3221a76c48765af0276f3aac02e5267178660b78932df16fb183745097f5aa47d1734e4c17be515a92126f76ac24c6a63ed14d7da640faf86f792",
          "sha256": "f450c1d4b32f2b32e7e4973c54ddc4bd419008e77da6888a050eb2d14488a755",
          "sha1": "6c75b27cf8f58835c93de2fe70cee55669d733f5",
          "md5": "732ef65f8659a0bc5b818bb438817450"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "br.com.fortface",
          "module": "fortface",
          "version": {
            "requires": "1.21.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "fortface",
              "type": "aar",
              "extension": "aar",
              "classifier": "release"
            }
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.2-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.2-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.2-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.2-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.2-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.2-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "fortfacesdk-2.0.2-beta.aar",
          "url": "fortfacesdk-2.0.2-beta.aar",
          "size": 240374,
          "sha512": "bccc2c04c5c3221a76c48765af0276f3aac02e5267178660b78932df16fb183745097f5aa47d1734e4c17be515a92126f76ac24c6a63ed14d7da640faf86f792",
          "sha256": "f450c1d4b32f2b32e7e4973c54ddc4bd419008e77da6888a050eb2d14488a755",
          "sha1": "6c75b27cf8f58835c93de2fe70cee55669d733f5",
          "md5": "732ef65f8659a0bc5b818bb438817450"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fortfacesdk-2.0.2-beta-sources.jar",
          "url": "fortfacesdk-2.0.2-beta-sources.jar",
          "size": 81999,
          "sha512": "73e9bab68d23a5872aaa0a5c35391e0ba6b50fe88330985adf50712c11520de51c3b49efb4bce4fff2a0041ee2efb598e604fa3ed04032f5722050fd1f1ae397",
          "sha256": "8496521a33e0115d8de4c53695b30338b0648b62faa5dbb648fd765f0cd76805",
          "sha1": "82f5fa382ca7516baeb030d4655354ebb8b6fbdd",
          "md5": "b327f4b2d3c509480d4c37531155d3cb"
        }
      ]
    }
  ]
}
