{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "0.0.18-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.18-test.aar",
          "url": "data-0.0.18-test.aar",
          "size": 194276,
          "sha512": "f4163e4a011037401cfbb90163749a7c4fc3c6978311b04a232384858b9e8bcf2bd23af3bf5ffdc66e2ee250675d822354064feac4d9cacb8d95210ec8f088da",
          "sha256": "f6a20859513868c5aa0438a4c91e721ef1ca66b83dce2dd5e6bd49be974c16eb",
          "sha1": "08514cfaa612401a7d6592a22a95b3e5f53d7b02",
          "md5": "0d7c5be8543dd795396aca85ad009fd3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.18-test"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.18-test.aar",
          "url": "data-0.0.18-test.aar",
          "size": 194276,
          "sha512": "f4163e4a011037401cfbb90163749a7c4fc3c6978311b04a232384858b9e8bcf2bd23af3bf5ffdc66e2ee250675d822354064feac4d9cacb8d95210ec8f088da",
          "sha256": "f6a20859513868c5aa0438a4c91e721ef1ca66b83dce2dd5e6bd49be974c16eb",
          "sha1": "08514cfaa612401a7d6592a22a95b3e5f53d7b02",
          "md5": "0d7c5be8543dd795396aca85ad009fd3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-0.0.18-test-sources.jar",
          "url": "data-0.0.18-test-sources.jar",
          "size": 27346,
          "sha512": "003e71dc9014c98490e36009dda554a665106293ba425adeec715e2aecbe7547123b3481326738882d91198c94597896ee0e12e7ad3c72fdb4b73617bd5b4fd6",
          "sha256": "d709a016643baf4632cea17d995fe45fe8bc0ebfe4138e089963a8b173427fd2",
          "sha1": "97ea5e43a4e7e6b885a049002ca4aa90444b120f",
          "md5": "5b3027ab21e5d37605a41246a433ce2a"
        }
      ]
    }
  ]
}
