{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "1.2.1-iproov-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.2.1-iproov-snapshot.aar",
          "url": "designsystem-1.2.1-iproov-snapshot.aar",
          "size": 1887184,
          "sha512": "dd74106935349cb0bb94dd4c37fec1690367a2f240e9f311b144b4fbcda25a23f412f360d61844c20cd2475766a796746b536161e6bf5ec58f4ab28a6dfffcf0",
          "sha256": "6add7f7c80bd28f659922aee33ab679564068bca140a55902126d976b3b4c21c",
          "sha1": "248c8bac955f05aa4233a855e7d2bb7df23bedb6",
          "md5": "db98b89c65a4ec35d8563584a565069b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.2.1-iproov-snapshot.aar",
          "url": "designsystem-1.2.1-iproov-snapshot.aar",
          "size": 1887184,
          "sha512": "dd74106935349cb0bb94dd4c37fec1690367a2f240e9f311b144b4fbcda25a23f412f360d61844c20cd2475766a796746b536161e6bf5ec58f4ab28a6dfffcf0",
          "sha256": "6add7f7c80bd28f659922aee33ab679564068bca140a55902126d976b3b4c21c",
          "sha1": "248c8bac955f05aa4233a855e7d2bb7df23bedb6",
          "md5": "db98b89c65a4ec35d8563584a565069b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.2.1-iproov-snapshot-sources.jar",
          "url": "designsystem-1.2.1-iproov-snapshot-sources.jar",
          "size": 34308,
          "sha512": "985052ab05e903063f5594787a287df04782c0e29f79c8687b98d4aa9cc17f547dfbd0b07c0dfe8150203d102d4e0ea7fe099a1e234da3215bc86629d9668462",
          "sha256": "4ec6839aa5b2ee03adaa118c5e464bc6bbc6c76edbf6dce8b89e5e2be179e40a",
          "sha1": "c0ee49930bec25893fdb339346169f8bb836866b",
          "md5": "61e623126e529ecc4ffaf7177bc5eebc"
        }
      ]
    }
  ]
}
