{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "core",
    "version": "2.0.0-beta-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.0.0-beta-1.aar",
          "url": "core-2.0.0-beta-1.aar",
          "size": 12381,
          "sha512": "9d2124663931021761e1bceedc11498e24d2d9db8dc8d78a3b6ec84130b0f6f010f09bbe5e117b649c4bf152bc36037fe68418a65ee8ccf69249ee0daa1d05a0",
          "sha256": "1988599b78717f235efc0b101ec460b7d735f7135cf178254eace83feca12dcd",
          "sha1": "db466f1485118792284c810aed84b95beb2161db",
          "md5": "03faffd104fb8ab67e5a0b9e13074713"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.0.0-beta-1.aar",
          "url": "core-2.0.0-beta-1.aar",
          "size": 12381,
          "sha512": "9d2124663931021761e1bceedc11498e24d2d9db8dc8d78a3b6ec84130b0f6f010f09bbe5e117b649c4bf152bc36037fe68418a65ee8ccf69249ee0daa1d05a0",
          "sha256": "1988599b78717f235efc0b101ec460b7d735f7135cf178254eace83feca12dcd",
          "sha1": "db466f1485118792284c810aed84b95beb2161db",
          "md5": "03faffd104fb8ab67e5a0b9e13074713"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-2.0.0-beta-1-sources.jar",
          "url": "core-2.0.0-beta-1-sources.jar",
          "size": 4874,
          "sha512": "18ebb6222745370645284477b3e8394aace3e1c46160e992836f6be0a70f648b8142e4ced0935efd07ea9be1f7bdaf0f6df58cd010df18466d3fea20a9a37136",
          "sha256": "a3f2b26f29135dc422f2bc336eabc9138c538ae2f0fafa96489ea471bab9e614",
          "sha1": "26df72e62c67e89f082021a61c997415064bea2f",
          "md5": "999ccab0ae63e8db66281c5e34d1899e"
        }
      ]
    }
  ]
}
