{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.2.aar",
          "url": "domain-1.2.2.aar",
          "size": 170414,
          "sha512": "b3ee618afdf0b79560bbf611bc747cd0f3a9d9b9705615ed46ebb256775e350880627816eb8c125f00da41792d2acc8105155dda5364e2ad89e293f7149c18d1",
          "sha256": "452ac39c7bfb17a0d67031f6e7b278bac3d3a969c4f29c6c1db3ec072949bc55",
          "sha1": "94616174ee37402f159ad0162808edb8ba0abaa4",
          "md5": "dc98117d227b76b2e51a64259e3e7829"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.2.2.aar",
          "url": "domain-1.2.2.aar",
          "size": 170414,
          "sha512": "b3ee618afdf0b79560bbf611bc747cd0f3a9d9b9705615ed46ebb256775e350880627816eb8c125f00da41792d2acc8105155dda5364e2ad89e293f7149c18d1",
          "sha256": "452ac39c7bfb17a0d67031f6e7b278bac3d3a969c4f29c6c1db3ec072949bc55",
          "sha1": "94616174ee37402f159ad0162808edb8ba0abaa4",
          "md5": "dc98117d227b76b2e51a64259e3e7829"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.2.2-sources.jar",
          "url": "domain-1.2.2-sources.jar",
          "size": 42452,
          "sha512": "c70838149742df44662b6ef86ebe16bec4c23fa4d28fb33947f44798dcd8e1c73cba6ecd39f6d953f4d96421b24890e518332123b3732f97888a18027bfdedb1",
          "sha256": "eccece373c804abd0a4a285e61676a85d25b0e953eae15a79f5be95fd3cab02a",
          "sha1": "83ba615a099ea9731ed4c0c625269663e307642d",
          "md5": "9e0663694c83405404f271fad8cff71a"
        }
      ]
    }
  ]
}
